#!/usr/bin/env bash
# Creates the knowledge-layer review epic + sub-issues on GitHub, cross-links
# them, attaches each child as a sub-issue, and writes the checklist onto the
# epic. Needs: gh (authenticated with issues:write on the repo), jq.
#
#   ./create-issues.sh                 # create everything in Claudfather/Claudron
#   REPO=owner/name ./create-issues.sh # another repo
#   DRY_RUN=1 ./create-issues.sh       # print what would be created
#
# Re-runnable: created issues are recorded in .created.tsv next to this script
# and skipped on a re-run, so a failure part-way can simply be retried.
set -euo pipefail

REPO="${REPO:-Claudfather/Claudron}"
DIR="$(cd "$(dirname "$0")" && pwd)"
STATE="$DIR/.created.tsv"
FOOTER=$'\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_'
touch "$STATE"

title_of()  { sed -n '1s/^TITLE: //p' "$1"; }
labels_of() { sed -n '2s/^LABELS: //p' "$1"; }
body_of()   { tail -n +4 "$1"; }
key_of()    { basename "$1" .md | sed 's/^[0-9]*-//'; }
lookup()    { awk -F'\t' -v k="$1" '$1==k{print $2}' "$STATE"; }

create() {  # key file extra_body -> prints issue number
  local key=$1 file=$2 extra=${3:-} num
  num=$(lookup "$key")
  if [ -n "$num" ]; then echo "$num"; return; fi
  local args=(--repo "$REPO" --title "$(title_of "$file")")
  IFS=',' read -ra labels <<<"$(labels_of "$file")"
  for l in "${labels[@]}"; do [ -n "$l" ] && args+=(--label "$l"); done
  local body; body="$(body_of "$file")$extra$FOOTER"
  if [ -n "${DRY_RUN:-}" ]; then
    echo "DRY: create [$key] $(title_of "$file")" >&2; num=$((9000 + $(wc -l <"$STATE")))
  else
    url=$(gh issue create "${args[@]}" --body "$body")
    num=${url##*/}
  fi
  printf '%s\t%s\n' "$key" "$num" >>"$STATE"
  echo "$num"
}

# 1. Epic
EPIC=$(create epic "$DIR/epic.md" $'\n_(children being created…)_')
echo "epic: #$EPIC" >&2

# 2. Children (placeholders resolved in pass 3)
for f in "$DIR"/children/*.md; do
  n=$(create "$(key_of "$f")" "$f")
  echo "  #$n  $(title_of "$f")" >&2
done

# 3. Resolve {{key}} cross-links, attach as sub-issues
render() {  # file -> body with every {{key}} replaced by its issue number
  local b; b="$(body_of "$1")"
  while IFS=$'\t' read -r k n; do b="${b//\{\{$k\}\}/$n}"; done <"$STATE"
  b="${b//\{\{EPIC\}\}/$EPIC}"
  if grep -q '{{' <<<"$b"; then echo "unresolved placeholder in $1" >&2; exit 1; fi
  printf '%s%s' "$b" "$FOOTER"
}
checklist=""
for f in "$DIR"/children/*.md; do
  k=$(key_of "$f"); n=$(lookup "$k")
  checklist+=$'\n'"- [ ] #$n — $(title_of "$f")"
  [ -n "${DRY_RUN:-}" ] && continue
  gh issue edit "$n" --repo "$REPO" --body "$(render "$f")" >/dev/null
  id=$(gh api "repos/$REPO/issues/$n" --jq .id)
  gh api -X POST "repos/$REPO/issues/$EPIC/sub_issues" -F sub_issue_id="$id" >/dev/null 2>&1 \
    || echo "  (#$n already a sub-issue or sub-issues unavailable)" >&2
done

# 4. Epic checklist
if [ -z "${DRY_RUN:-}" ]; then
  gh issue edit "$EPIC" --repo "$REPO" \
    --body "$(body_of "$DIR/epic.md")$checklist$FOOTER" >/dev/null
fi
echo "done: https://github.com/$REPO/issues/$EPIC" >&2
