"""Claudron CLI — knowledge engine for Claude Code."""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

from . import __version__
from .engine import ScopeError, append_addendum, capture, compose_note, resolve_target_dir
from .schema import TYPES, Finding, slugify, validate_path
from .structure import StructureError, check_structure, fix_structure, is_fixable
from .vault import (
    SCAFFOLD_TREE,
    SKIP_DIRS,
    Vault,
    VaultError,
    detect,
    init,
    is_within_root,
    scaffold_shared_tree,
    status,
)
from .hooks import (
    HOOK_EVENTS,
    merge_settings,
    resolve_executable,
    run_hook,
    settings_snippet,
)
from .knowledge import build_index, load_index, lookup
from .session import derive_project, recall, render_brief
from .sync import SyncError, run_git, sync


# ── output contract (docs/CLI_CONTRACT.md) ────────────────────────────
#
# stdout carries payload only (session hooks inject it verbatim);
# diagnostics go to stderr. --json emits exactly one envelope on stdout.


def _envelope(command: str, data: dict, findings: list[Finding] | None = None) -> dict:
    errors = [f.to_dict() for f in findings or [] if f.severity == "error"]
    warnings = [f.to_dict() for f in findings or [] if f.severity == "warning"]
    return {
        "ok": not errors,
        "command": command,
        "data": data,
        "warnings": warnings,
        "errors": errors,
    }


def _emit_json(command: str, data: dict, findings: list[Finding] | None = None) -> None:
    print(json.dumps(_envelope(command, data, findings), indent=2, default=str))


# ── vault resolution ──────────────────────────────────────────────────


def _detect_vault(args) -> Vault | None:
    """The resolution chain, policy-free (docs/CLI_CONTRACT.md order):
    --vault flag → $CLAUDRON_VAULT_PATH → $CLAUDRON_VAULT → walk-up.
    _resolve_vault adds exit-3-on-None; hooks pass None through (fail-open
    contract). CLAUDRON_VAULT_PATH is the var Claudlobby emits per bot
    (composer.py) — reading it is what makes the CLI the fleet's contract floor."""
    vault_hint = (
        getattr(args, "vault", None)
        or os.environ.get("CLAUDRON_VAULT_PATH")
        or os.environ.get("CLAUDRON_VAULT")
    )
    return detect(Path(vault_hint)) if vault_hint else detect()


def _resolve_vault(args) -> Vault:
    """Resolve vault or exit 3 (environment error, CLI contract)."""
    vault = _detect_vault(args)
    if vault is None:
        print(
            "no vault found\n"
            "  create one:  claudron init <path>\n"
            "  or specify:  claudron --vault <path> <command>",
            file=sys.stderr,
        )
        sys.exit(3)  # environment error (docs/CLI_CONTRACT.md; was 2 pre-0.2.0)
    return vault


# ── .claudron config ─────────────────────────────────────────────────


def _detect_claudlobby_root(hint: Path | None = None) -> Path | None:
    """Walk up from *hint* (or CWD) looking for a claudlobby repo root.

    Marker: directory containing both ``library/`` and ``lib/``.
    """
    start = (hint or Path.cwd()).resolve()
    for candidate in [start, *start.parents]:
        if (candidate / "library").is_dir() and (candidate / "lib").is_dir():
            return candidate
    return None


def _require_claudlobby_root(args, command: str) -> Path:
    """Resolve claudlobby root or exit with a clear error."""
    cl_root = _detect_claudlobby_root(_claudlobby_hint(args))
    if cl_root is None:
        print(
            f"could not find claudlobby root\n"
            f"  {command} requires a claudlobby installation\n"
            f"  specify with: claudron {command} --claudlobby <path>",
            file=sys.stderr,
        )
        sys.exit(3)  # environment error (docs/CLI_CONTRACT.md; was 2 pre-0.2.0)
    return cl_root


def _read_claudron_config(path: Path) -> dict[str, str]:
    """Read shell-sourceable ``.claudron`` config file. Returns parsed key=value pairs."""
    result: dict[str, str] = {}
    if not path.is_file():
        return result
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, _, val = line.partition("=")
            result[key.strip()] = val.strip()
    return result


def _write_claudron_config(path: Path, vault_path: Path) -> None:
    """Write ``.claudron`` config pointing to vault."""
    path.write_text(
        f"# .claudron — auto-generated by claudron plug\nvault={vault_path}\n"
    )


# ── commands ──────────────────────────────────────────────────────────


def cmd_init(args) -> int:
    path = Path(args.path).expanduser()
    try:
        root = init(path, adopt=args.adopt)
    except VaultError as e:
        print(str(e), file=sys.stderr)
        return 2

    if getattr(args, "personal", False):
        return _init_personal(args, root)

    if args.json:
        _emit_json(
            "init",
            {"root": str(root), "scaffold": [f"_shared/{n}" for n in SCAFFOLD_TREE]},
        )
        return 0
    print(f"vault created at {root}")
    for name in SCAFFOLD_TREE:
        print(f"  _shared/{name}/")
    print("  projects/")
    print("next: claudron validate   (audits the vault's structure)", file=sys.stderr)
    return 0


def _init_personal(args, root: Path) -> int:
    """The two-command bootstrap (E2): vault + git repo + a real first
    note proving the loop, then the machine-B one-liners. The smoke test
    is honest — a broken loop reports, it doesn't hide (verify mandate)."""
    from datetime import date

    # Git repo: init only when the vault isn't already inside one — never
    # re-init or commit over user history (--adopt case). run_git maps a
    # missing git binary to SyncError → clean exit 3 instead of a
    # traceback on the exact fresh machine this command targets.
    try:
        if run_git(root, "rev-parse", "--git-dir").returncode != 0:
            made = run_git(root, "init", "--initial-branch=main")
            if made.returncode != 0:
                print(
                    f"git init failed: {made.stderr.strip()[:200]}",
                    file=sys.stderr,
                )
                return 3
    except SyncError as exc:
        print(f"{exc} — the SD card needs git", file=sys.stderr)
        return 3  # environment error

    # Doctor-style smoke test as a REAL first note: capture through the
    # engine, then prove recall serves it. Bootstraps trust in the loop.
    vault = detect(root)
    try:
        result = capture(
            vault,
            note_type="knowledge",
            title="Vault Bootstrap",
            body=(
                f"Vault created {date.today().isoformat()} via "
                "`claudron init --personal`. Captures land as maturity: "
                "draft; promote what proves true."
            ),
            owner=_derive_owner(args),
        )
        smoke_ok = result.action == "created"
        if smoke_ok:
            data = recall(vault, project=None, query="vault bootstrap")
            smoke_ok = any(
                n["title"] == "Vault Bootstrap" for n in data["notes"]
            )
    except Exception as exc:
        print(f"smoke test failed: {exc}", file=sys.stderr)
        return 1
    if not smoke_ok:
        print(
            "smoke test failed: bootstrap note not served by recall",
            file=sys.stderr,
        )
        return 1

    # Commit the scaffold + bootstrap note so machine B's clone gets it —
    # and say so when it fails (unset git identity is the common cause;
    # an unconditional success message would tell the user to push a
    # commit that doesn't exist). No SyncError catch here by design: git
    # presence is proven by rev-parse above and no timeout is passed, so
    # run_git cannot raise on this path.
    seed_msg = "claudron init --personal"
    run_git(root, "add", "-A")
    committed = run_git(root, "commit", "-m", seed_msg).returncode == 0
    if not committed:
        print(
            "warning: seed commit failed (git identity unset?) — run\n"
            f"  git -C {root} -c user.name=YOU -c user.email=YOU@example.com "
            f"commit -m '{seed_msg}'\n"
            "before pushing to a remote",
            file=sys.stderr,
        )

    if args.json:
        _emit_json(
            "init",
            {
                "root": str(root),
                "personal": True,
                "smoke_test": "passed",
                "committed": committed,
            },
        )
        return 0

    print(f"personal vault ready at {root}")
    print("smoke test: recall found the bootstrap note ✓")
    print()
    print("next steps:")
    print(f"  1. install the session hooks:   claudron --vault {root} hooks install --write")
    print(f"  2. add your private remote:     git -C {root} remote add origin <url> && git -C {root} push -u origin main")
    print(f"  3. on your other machine:       git clone <url> && claudron hooks install --write")
    print(f"  4. point sessions at the vault: export CLAUDRON_VAULT={root}")
    return 0


def cmd_status(args) -> int:
    vault = _resolve_vault(args)
    info = status(vault, stale_days=getattr(args, "stale_days", 90))

    if args.json:
        _emit_json("status", info)
        return 0

    print(f"vault: {info['root']}")
    print(f"docs:  {info['total_docs']}  stale: {info['total_stale']}")
    if info["fleets"]:
        print(f"fleets: {', '.join(info['fleets'])}")
    if info["projects"]:
        print(f"projects: {', '.join(info['projects'])}")
    print()
    for tier_name, tier_info in info["tiers"].items():
        if tier_info["docs"] > 0 or args.verbose:
            stale_str = f"  ({tier_info['stale']} stale)" if tier_info["stale"] else ""
            print(f"  {tier_name}: {tier_info['docs']} docs{stale_str}")

    # Index state + vault warnings are diagnostics, not payload → stderr
    if not info["index_present"]:
        print("index: not built (will auto-build on first lookup)", file=sys.stderr)
    elif not info["index_fresh"]:
        print("index: stale (will auto-rebuild on next lookup)", file=sys.stderr)
    for w in info["warnings"]:
        print(f"warning: {w}", file=sys.stderr)
    return 0


def cmd_lookup(args) -> int:
    vault = _resolve_vault(args)
    query = " ".join(args.query)
    results = lookup(
        query,
        vault,
        project=args.project,
        fleet=args.fleet,
        limit=args.limit,
        include_archived=args.include_archived,
        include_expired=args.include_expired,
    )

    if not results:
        if args.json:
            _emit_json("lookup", {"query": query, "results": []})
        else:
            print(f"no results for '{query}'", file=sys.stderr)
        return 0

    if args.json:
        _emit_json(
            "lookup",
            {
                "query": query,
                "results": [
                    {
                        "title": r.doc.title,
                        "score": r.score,
                        "match_type": r.match_type,
                        "tier": r.doc.tier,
                        "path": str(r.doc.source_path.relative_to(vault.root)),
                        "tags": r.doc.tags,
                    }
                    for r in results
                ],
            },
        )
        return 0

    for r in results:
        rel = r.doc.source_path.relative_to(vault.root)
        tags = f"  [{', '.join(r.doc.tags)}]" if r.doc.tags else ""
        print(f"  [{r.score:3d}] {r.doc.title:<40s} {rel}{tags}")
    return 0


def cmd_index(args) -> int:
    vault = _resolve_vault(args)

    existing = None if args.full else load_index(vault)
    if existing is not None:
        count, rebuilt = len(existing.get("entries", [])), False
        msg = f"index up to date ({count} entries)"
    else:
        count, rebuilt = len(build_index(vault).get("entries", [])), True
        msg = f"indexed {count} docs"

    if args.json:
        _emit_json("index", {"entries": count, "rebuilt": rebuilt})
    else:
        print(msg, file=sys.stderr)
    return 0


def cmd_version(args) -> int:
    if args.json:
        _emit_json("version", {"version": __version__})
    else:
        print(f"claudron {__version__}")
    return 0


def _derive_owner(args) -> str:
    """--owner → git config user.name → $USER (docs/CLI_CONTRACT.md)."""
    if getattr(args, "owner", None):
        return args.owner
    import subprocess

    try:
        name = subprocess.run(
            ["git", "config", "user.name"], capture_output=True, text=True, timeout=5
        ).stdout.strip()
        if name:
            return name
    except (OSError, subprocess.TimeoutExpired):
        # TimeoutExpired is a SubprocessError, NOT an OSError — without
        # naming it, the timeout guard guards nothing (review minor 6).
        pass
    return os.environ.get("USER", "unknown")


def cmd_new(args) -> int:
    vault = _resolve_vault(args)
    title = args.title

    try:
        base = resolve_target_dir(
            vault, args.type, project=args.project, fleet=args.fleet
        )
    except ScopeError as exc:
        print(str(exc), file=sys.stderr)
        return 2
    base.mkdir(parents=True, exist_ok=True)

    target = base / f"{slugify(title)}.md"
    if target.exists() and not args.force:
        print(
            f"note already exists: {target}\n  pass --force to overwrite",
            file=sys.stderr,
        )
        return 1

    target.write_text(
        compose_note(
            note_type=args.type,
            title=title,
            owner=_derive_owner(args),
            tags=args.tags.split(",") if args.tags else None,
        )
    )

    if args.edit:
        editor = os.environ.get("EDITOR")
        if editor:
            import subprocess

            subprocess.run([editor, str(target)])
        else:
            print("$EDITOR is not set — note written, not opened", file=sys.stderr)

    if args.json:
        _emit_json("new", {"path": str(target)})
    else:
        print(str(target))
    return 0


def cmd_capture(args) -> int:
    vault = _resolve_vault(args)

    if args.update:
        note_path = vault.root / args.update
        if not is_within_root(note_path, vault.root) or not note_path.is_file():
            print(f"no such note in vault: {args.update}", file=sys.stderr)
            return 2
        if not args.body:
            print("--update requires --body", file=sys.stderr)
            return 2
        try:
            result = append_addendum(vault, note_path, args.body)
        except ScopeError as exc:
            print(str(exc), file=sys.stderr)
            return 2
        return _emit_write_result(args, result)

    if args.stdin:
        try:
            finding = json.loads(sys.stdin.read())
        except json.JSONDecodeError as exc:
            print(f"invalid JSON on stdin: {exc}", file=sys.stderr)
            return 2
    else:
        finding = {}
    note_type = finding.get("type") or args.type
    title = finding.get("title") or args.title
    body = finding.get("body") or args.body or ""
    if not note_type or not title:
        print("capture requires --type and --title (or --stdin JSON)", file=sys.stderr)
        return 2
    tags = finding.get("tags") or (
        [t.strip() for t in args.tags.split(",")] if args.tags else None
    )
    owner = finding.get("owner") or _derive_owner(args)

    try:
        result = capture(
            vault,
            note_type=note_type,
            title=title,
            body=body,
            owner=owner,
            tags=tags,
            project=finding.get("project") or args.project,
            fleet=finding.get("fleet") or args.fleet,
            force=args.force,
        )
    except ScopeError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    return _emit_write_result(args, result)


def _emit_write_result(args, result) -> int:
    """One WriteResult renderer for the write commands (capture --update
    shares it): rejected → findings + exit 1, else action/path + exit 0.

    ``written`` is the load-bearing signal: exit 0 and ``ok:true`` mean the
    command *succeeded*, not that a note landed — a ``suggest_*`` dedup route
    succeeds having written nothing. A programmatic caller (a clauDNA skill
    wrapping the CLI) must branch on ``written`` / ``action``, never on the exit
    code, or it silently drops the deduped finding (docs/CLI_CONTRACT.md)."""
    written = result.action in ("created", "updated")
    if result.action == "rejected":
        if args.json:
            _emit_json(
                "capture",
                {"action": result.action, "path": result.path,
                 "reason": result.reason, "written": False},
                result.errors,
            )
        else:
            for f in result.errors:
                print(f"[{f.code}] {f.severity} — {f.message}", file=sys.stderr)
        return 1

    if args.json:
        _emit_json(
            "capture",
            {"action": result.action, "path": result.path,
             "reason": result.reason, "written": written},
        )
    else:
        print(f"{result.action}: {result.path}")
        if result.action.startswith("suggest_"):
            print(result.reason, file=sys.stderr)
            print("note: nothing written — this is a dedup suggestion, not a "
                  "save (re-run with --update or --force)", file=sys.stderr)
    return 0


def cmd_recall(args) -> int:
    vault = _resolve_vault(args)
    # A derived name with no matching project tier still contributes as
    # the shared-tier relevance term — recall() handles both roles.
    project = args.project or derive_project()
    query = " ".join(args.query) if args.query else None
    data = recall(vault, project=project, query=query, limit=args.limit)

    if args.json:
        _emit_json("recall", data)
        return 0

    brief = render_brief(data)
    if brief:
        print(brief)
    else:
        # Abstention: inject nothing rather than something (stderr only).
        print("no context recalled", file=sys.stderr)
    return 0


def cmd_sync(args) -> int:
    vault = _resolve_vault(args)
    if args.pull_only:
        pull, push = True, False
    elif args.push_only:
        pull, push = False, True
    else:
        pull, push = True, True
    try:
        result = sync(vault, pull=pull, push=push, timeout=args.timeout)
    except SyncError as exc:
        print(str(exc), file=sys.stderr)
        return 3  # environment error (CLI contract)

    if args.json:
        _emit_json("sync", result.to_dict())
    else:
        parts = [
            name
            for name, done in (
                ("committed", result.committed),
                ("pulled", result.pulled),
                ("pushed", result.pushed),
            )
            if done
        ]
        print(f"sync: {', '.join(parts) if parts else 'nothing to do'}")
        if result.detail:
            print(result.detail, file=sys.stderr)
        for path in result.quarantined:
            print(f"conflict — quarantined until resolved: {path}", file=sys.stderr)
    return 0 if result.ok else 1


def cmd_hook(args) -> int:
    """Hook entry points: lenient vault resolution (None passes through —
    fail-open), then the guarded dispatch (run_hook owns the contract)."""
    return run_hook(args.event, _detect_vault(args))


def cmd_hooks_install(args) -> int:
    snippet = settings_snippet(resolve_executable())
    if not args.write:
        print(json.dumps(snippet, indent=2))
        print(
            "\nmerge into ~/.claude/settings.json (or rerun with --write)",
            file=sys.stderr,
        )
        return 0

    settings_path = Path(
        args.settings or Path.home() / ".claude" / "settings.json"
    ).expanduser()
    current: dict = {}
    if settings_path.is_file():
        try:
            current = json.loads(settings_path.read_text())
        except json.JSONDecodeError:
            print(f"cannot parse {settings_path} — not touching it", file=sys.stderr)
            return 3
    merged = merge_settings(current, snippet)
    if merged == current:
        print("hooks already installed — no changes", file=sys.stderr)
        return 0
    print(f"writing {settings_path}", file=sys.stderr)
    settings_path.parent.mkdir(parents=True, exist_ok=True)
    settings_path.write_text(json.dumps(merged, indent=2) + "\n")
    return 0


def cmd_validate(args) -> int:
    strict = args.strict
    fix = args.fix
    vault = None
    if args.path:
        target = Path(args.path).expanduser().resolve()
        if not target.exists():
            print(f"no such path: {target}", file=sys.stderr)
            return 2
        # Vault context (for relative paths + shared-root rules) when the
        # target sits inside one; otherwise the target anchors itself.
        # Note: an explicit PATH anchors to its own vault — --vault is
        # deliberately not consulted here.
        probe = target if target.is_dir() else target.parent
        anchor = detect(probe)
        findings = validate_path(
            target, strict=strict, vault_root=anchor.root if anchor else probe
        )
        # The structure lens is whole-vault, so only when the target IS a
        # vault root — never for a single note or an inner subtree.
        if anchor and target == anchor.root:
            vault = anchor
    else:
        vault = _resolve_vault(args)
        findings = validate_path(vault.root, strict=strict, vault_root=vault.root)

    findings = list(findings)
    if vault is not None:
        structure = check_structure(vault, strict=strict)
        if fix:
            try:
                actions = fix_structure(vault, structure)
            except StructureError as e:
                print(f"--fix aborted: {e}", file=sys.stderr)
                return 1
            for action in actions:
                print(action, file=sys.stderr)
            structure = check_structure(vault, strict=strict)  # reflect repairs
        findings += structure
    elif fix:
        print(
            "--fix needs a whole vault — omit PATH or pass the vault root",
            file=sys.stderr,
        )
        return 2

    errors = [f for f in findings if f.severity == "error"]
    warnings = [f for f in findings if f.severity == "warning"]

    if args.json:
        _emit_json(
            "validate",
            {"errors": len(errors), "warnings": len(warnings), "strict": strict},
            findings,
        )
        return 1 if errors else 0

    for f in findings:
        loc = f.path + (f":{f.line}" if f.line else "")
        print(f"[{f.code}] {f.severity} {loc} — {f.message}")
    print(
        f"{len(errors)} error(s), {len(warnings)} warning(s)"
        + (" [strict]" if strict else ""),
        file=sys.stderr,
    )
    # No silent switch: name the --fix escape hatch when repairs are available.
    if not fix:
        fixable = [f for f in findings if is_fixable(f)]
        if fixable:
            print(
                f"→ {len(fixable)} fixable — run: claudron validate --fix",
                file=sys.stderr,
            )
    return 1 if errors else 0


# ── Phase 2: claudlobby integration commands ─────────────────────────


def cmd_plug(args) -> int:
    vault_path = Path(args.vault_path).expanduser().resolve()
    if not any((vault_path / m).is_dir() for m in ("_shared", "shared")):
        print(
            f"not a vault: {vault_path} (no _shared/ or shared/ directory)",
            file=sys.stderr,
        )
        return 2

    cl_root = _require_claudlobby_root(args, "plug")

    config_path = cl_root / ".claudron"
    old_config = _read_claudron_config(config_path)
    old_vault = old_config.get("vault")
    if old_vault:
        print(f"replacing existing config (was: {old_vault})")
    _write_claudron_config(config_path, vault_path)
    print(f"plugged vault {vault_path}")
    print(f"  config: {config_path}")
    return 0


def cmd_unplug(args) -> int:
    cl_root = _require_claudlobby_root(args, "unplug")

    config_path = cl_root / ".claudron"
    if not config_path.is_file():
        print("no .claudron config to remove", file=sys.stderr)
        return 1

    config_path.unlink()
    print(f"unplugged (removed {config_path})")
    return 0


def _claudlobby_hint(args) -> Path | None:
    """Extract --claudlobby hint from args."""
    raw = getattr(args, "claudlobby", None)
    return Path(raw).resolve() if raw else None


def cmd_config(args) -> int:
    cl_root = _detect_claudlobby_root(_claudlobby_hint(args))

    info: dict = {"claudlobby_root": str(cl_root) if cl_root else None}

    vault_path = None
    if cl_root:
        config = _read_claudron_config(cl_root / ".claudron")
        vault_str = config.get("vault")
        if vault_str:
            vault_path = Path(vault_str)
            info["vault"] = str(vault_path)
            info["config_file"] = str(cl_root / ".claudron")

    if vault_path and vault_path.is_dir():
        vault = detect(vault_path)
        if vault:
            info["fleets"] = list(vault.fleets.keys())
    else:
        info["vault"] = None

    if args.json:
        _emit_json("config", info)
    else:
        print(f"claudlobby: {info['claudlobby_root'] or '(not found)'}")
        print(f"vault:      {info.get('vault') or '(not plugged)'}")
        if info.get("fleets"):
            print(f"fleets:     {', '.join(info['fleets'])}")
    return 0


_FLEET_YAML_TEMPLATE = """\
fleet:
  name: {name}
  service_prefix: com.example.{name}
  bots: {{}}
"""


_RESERVED_FLEET_NAMES = SKIP_DIRS


def cmd_fleet_add(args) -> int:
    vault = _resolve_vault(args)
    name = args.name

    if name in _RESERVED_FLEET_NAMES:
        print(
            f"'{name}' is a reserved name and cannot be used as a fleet name",
            file=sys.stderr,
        )
        return 2

    fleet_dir = vault.root / name
    if fleet_dir.exists():
        print(f"fleet directory already exists: {fleet_dir}", file=sys.stderr)
        return 2

    fleet_dir.mkdir()
    (fleet_dir / "fleet.yaml").write_text(_FLEET_YAML_TEMPLATE.format(name=name))
    scaffold_shared_tree(fleet_dir / "shared")
    (fleet_dir / ".env").write_text("# Fleet secrets — never commit\n")
    (fleet_dir / ".gitignore").write_text("runtime/\n.env\n")

    print(f"fleet '{name}' scaffolded at {fleet_dir}")
    return 0


def cmd_fleet_list(args) -> int:
    vault = _resolve_vault(args)
    if not vault.fleets:
        print("no fleets in vault")
        return 0
    for name in sorted(vault.fleets):
        print(f"  {name}")
    return 0


def cmd_migrate(args) -> int:
    import shutil

    vault = _resolve_vault(args)
    fleet_name = args.fleet
    apply = args.apply
    force = getattr(args, "force", False)

    # Find claudlobby root to locate local/<fleet>/
    cl_root = _require_claudlobby_root(args, "migrate")

    source = cl_root / "local" / fleet_name
    if not source.is_dir():
        print(f"source not found: {source}", file=sys.stderr)
        return 2

    dest = vault.root / fleet_name
    if not dest.is_dir():
        print(
            f"fleet dir not in vault: {dest}\n  run: claudron fleet add {fleet_name}",
            file=sys.stderr,
        )
        return 2

    # Determine what to copy and detect overwrites
    copyable = ("shared", "library", "voices")
    plan: list[tuple[Path, Path]] = []
    for dirname in copyable:
        src = source / dirname
        if src.is_dir():
            plan.append((src, dest / dirname))

    # Memory dirs: look in runtime/bots/*/memory/
    runtime_bots = source / "runtime" / "bots"
    memory_plan: list[tuple[Path, Path]] = []
    if runtime_bots.is_dir():
        for bot_dir in sorted(runtime_bots.iterdir()):
            mem = bot_dir / "memory"
            if mem.is_dir() and any(mem.iterdir()):
                memory_plan.append(
                    (mem, dest / "runtime" / "bots" / bot_dir.name / "memory")
                )

    if not plan and not memory_plan:
        print("nothing to migrate")
        return 0

    # Build detailed file plan, distinguish new vs overwrite
    has_overwrites = False
    for src, dst in plan + memory_plan:
        is_memory = src in [m[0] for m in memory_plan]
        for item in sorted(src.rglob("*")):
            if item.is_dir():
                continue
            rel = item.relative_to(src)
            target = dst / rel
            overwrites = target.is_file()
            if overwrites:
                has_overwrites = True
            verb = "preserve" if is_memory else "copy"
            if not apply:
                verb = "would " + verb
            tag = " (overwrite)" if overwrites else " (new)"
            print(
                f"  {verb}: {item.relative_to(cl_root)} -> {target.relative_to(vault.root)}{tag}"
            )

    if not apply:
        print("\ndry run — pass --apply to execute")
        return 0

    if has_overwrites and not force:
        print(
            "\nsome files would be overwritten — pass --force to confirm",
            file=sys.stderr,
        )
        return 1

    # Execute
    for src, dst in plan + memory_plan:
        if dst.is_dir():
            for item in src.rglob("*"):
                rel = item.relative_to(src)
                target = dst / rel
                if item.is_dir():
                    target.mkdir(parents=True, exist_ok=True)
                else:
                    target.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(item, target)
        else:
            shutil.copytree(src, dst)

    print("\nmigration complete — verify with: claudron status")
    return 0


# ── main ──────────────────────────────────────────────────────────────


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        prog="claudron",
        description="Knowledge engine for Claude Code",
    )
    parser.add_argument("--vault", help="Vault path (default: detect from CWD)")
    sub = parser.add_subparsers(dest="command")

    # Shared parents (docs/CLI_CONTRACT.md): --vault/--json on subcommands
    # too, so `claudron status --json` and `claudron status --vault X` both
    # parse. Argparse only applies a subparser default when the attribute
    # is absent, so the top-level --vault value survives.
    # SUPPRESS is load-bearing: Python 3.14 argparse applies subparser
    # defaults over values the top-level parser already set, so a plain
    # default=None here would null out `claudron --vault X status`.
    vault_parent = argparse.ArgumentParser(add_help=False)
    vault_parent.add_argument(
        "--vault",
        default=argparse.SUPPRESS,
        help="Vault path (default: detect from CWD)",
    )
    json_parent = argparse.ArgumentParser(add_help=False)
    json_parent.add_argument(
        "--json", action="store_true", help="Emit the standard JSON envelope"
    )

    # init
    p_init = sub.add_parser(
        "init", help="Scaffold a new vault", parents=[json_parent]
    )
    p_init.add_argument("path", help="Where to create the vault")
    p_init.add_argument(
        "--adopt", action="store_true", help="Adopt an existing non-empty directory"
    )
    p_init.add_argument(
        "--personal",
        action="store_true",
        help="Bootstrap the SD card: vault + git repo + smoke-tested first "
        "note + machine-B one-liners",
    )
    p_init.add_argument(
        "--owner",
        help="Owner for the --personal bootstrap note "
        "(default: git user.name, then $USER)",
    )

    # status
    p_status = sub.add_parser(
        "status",
        help="Vault contents and health summary",
        parents=[vault_parent, json_parent],
    )
    p_status.add_argument(
        "--stale-days", type=int, default=90, help="Staleness threshold in days"
    )
    p_status.add_argument(
        "-v", "--verbose", action="store_true", help="Show empty tiers"
    )

    # validate
    p_validate = sub.add_parser(
        "validate",
        help="Lint notes (SCHEMA.md) + vault structure (VAULT-STRUCTURE.md)",
        parents=[vault_parent, json_parent],
    )
    p_validate.add_argument(
        "path",
        nargs="?",
        default=None,
        help="File or directory (default: the detected vault)",
    )
    p_validate.add_argument(
        "--strict",
        action="store_true",
        help="Authoring tier — what the engine/bot write paths enforce",
    )
    p_validate.add_argument(
        "--fix",
        action="store_true",
        help="Create missing structure (fleet shared/ dirs); "
        "creation-only, never moves or deletes",
    )

    # new
    p_new = sub.add_parser(
        "new",
        help="Scaffold a schema-valid note (passes validate --strict)",
        parents=[vault_parent, json_parent],
    )
    p_new.add_argument("type", choices=TYPES, help="Note type")
    p_new.add_argument("title", help="Note title")
    scope = p_new.add_mutually_exclusive_group()
    scope.add_argument("--project", help="File under projects/<name>/")
    scope.add_argument("--fleet", help="File under <fleet>/shared/")
    p_new.add_argument("--tags", help="Comma-separated tags")
    p_new.add_argument("--owner", help="Owner (default: git user.name, then $USER)")
    p_new.add_argument("--edit", action="store_true", help="Open in $EDITOR")
    p_new.add_argument(
        "--force", action="store_true", help="Overwrite an existing note"
    )

    # capture
    p_capture = sub.add_parser(
        "capture",
        help="Write a finding through the guarded engine (validate + dedup)",
        parents=[vault_parent, json_parent],
    )
    p_capture.add_argument("--type", choices=TYPES, help="Note type")
    p_capture.add_argument("--title", help="Note title")
    p_capture.add_argument("--body", help="Note body (markdown)")
    p_capture.add_argument("--tags", help="Comma-separated tags")
    p_capture.add_argument("--owner", help="Owner (default: git user.name, then $USER)")
    cap_scope = p_capture.add_mutually_exclusive_group()
    cap_scope.add_argument("--project", help="File under projects/<name>/")
    cap_scope.add_argument("--fleet", help="File under <fleet>/shared/")
    p_capture.add_argument(
        "--stdin", action="store_true",
        help="Read the finding as JSON from stdin (fields: type, title, body, tags, owner, project, fleet)",
    )
    p_capture.add_argument(
        "--update", metavar="PATH",
        help="Append a dated addendum to an existing note (vault-relative path) instead of creating",
    )
    p_capture.add_argument(
        "--force", action="store_true",
        help="Create even when dedup would suggest updating an existing note",
    )

    # recall
    p_recall = sub.add_parser(
        "recall",
        help="Session-start context brief (stdout is the injectable payload)",
        parents=[vault_parent, json_parent],
    )
    p_recall.add_argument(
        "--project", help="Project scope (default: derive from cwd git root)"
    )
    p_recall.add_argument(
        "--query", nargs="*", help="Relevance terms (default: the project name)"
    )
    p_recall.add_argument(
        "--limit", type=int, default=5, help="Notes per tier (default: 5)"
    )

    # sync
    p_sync = sub.add_parser(
        "sync",
        help="Commit vault changes, pull --rebase, push (the SD-card git leg)",
        parents=[vault_parent, json_parent],
    )
    sync_dir = p_sync.add_mutually_exclusive_group()
    sync_dir.add_argument(
        "--pull", dest="pull_only", action="store_true", help="Pull only"
    )
    sync_dir.add_argument(
        "--push", dest="push_only", action="store_true", help="Push only"
    )
    p_sync.add_argument(
        "--timeout", type=float, default=None, help="Seconds per git network op"
    )

    # hook (plumbing — invoked by Claude Code, fail-open by contract)
    p_hook = sub.add_parser(
        "hook",
        help="Hook entry points (SessionStart/PreCompact/SessionEnd plumbing)",
        parents=[vault_parent],
    )
    p_hook.add_argument("event", choices=HOOK_EVENTS)

    # hooks
    p_hooks = sub.add_parser(
        "hooks", help="Hook management", parents=[vault_parent]
    )
    hooks_sub = p_hooks.add_subparsers(dest="hooks_command")
    p_hooks_install = hooks_sub.add_parser(
        "install", help="Print (default) or --write the settings.json hooks block"
    )
    p_hooks_install.add_argument(
        "--write", action="store_true", help="Merge into settings.json (shows target)"
    )
    p_hooks_install.add_argument(
        "--settings", default=None,
        help="Settings file to merge into (default: ~/.claude/settings.json)",
    )

    # lookup
    p_lookup = sub.add_parser(
        "lookup", help="Search vault knowledge", parents=[vault_parent, json_parent]
    )
    p_lookup.add_argument("query", nargs="+", help="Search terms")
    p_lookup.add_argument("--project", help="Project context for scoped search")
    p_lookup.add_argument("--fleet", help="Fleet context for scoped search")
    p_lookup.add_argument(
        "--limit", type=int, default=5, help="Max results (default: 5)"
    )
    p_lookup.add_argument(
        "--include-archived",
        action="store_true",
        help="Include archived/completed docs",
    )
    p_lookup.add_argument(
        "--include-expired", action="store_true", help="Include expired docs"
    )

    # index
    p_index = sub.add_parser(
        "index",
        help="Build or rebuild the frontmatter index",
        parents=[vault_parent, json_parent],
    )
    p_index.add_argument(
        "--full", action="store_true", help="Force full rebuild even if fresh"
    )

    # version
    sub.add_parser("version", help="Print version", parents=[json_parent])

    # plug
    p_plug = sub.add_parser("plug", help="Register vault with claudlobby")
    p_plug.add_argument("vault_path", help="Path to vault")
    p_plug.add_argument(
        "--claudlobby", default=None, help="Claudlobby root (default: auto-detect)"
    )

    # unplug
    p_unplug = sub.add_parser("unplug", help="Disconnect vault from claudlobby")
    p_unplug.add_argument(
        "--claudlobby", default=None, help="Claudlobby root (default: auto-detect)"
    )

    # config
    p_config = sub.add_parser(
        "config", help="Show resolved config", parents=[json_parent]
    )
    p_config.add_argument(
        "--claudlobby", default=None, help="Claudlobby root (default: auto-detect)"
    )

    # fleet
    p_fleet = sub.add_parser("fleet", help="Fleet overlay management")
    fleet_sub = p_fleet.add_subparsers(dest="fleet_command")

    p_fleet_add = fleet_sub.add_parser("add", help="Scaffold fleet overlay in vault")
    p_fleet_add.add_argument("name", help="Fleet name")

    fleet_sub.add_parser("list", help="List fleets in vault")

    # migrate
    p_migrate = sub.add_parser(
        "migrate", help="Migrate local/<fleet>/ to vault (dry-run default)"
    )
    p_migrate.add_argument("--fleet", required=True, help="Fleet name to migrate")
    p_migrate.add_argument(
        "--apply", action="store_true", help="Execute migration (default: dry-run)"
    )
    p_migrate.add_argument(
        "--force", action="store_true", help="Allow overwriting existing files"
    )
    p_migrate.add_argument(
        "--claudlobby", default=None, help="Claudlobby root (default: auto-detect)"
    )

    args = parser.parse_args(argv)
    if not args.command:
        parser.print_help()
        return 1

    # Handle fleet subcommands
    if args.command == "fleet":
        if not getattr(args, "fleet_command", None):
            p_fleet.print_help()
            return 1
        fleet_dispatch = {
            "add": cmd_fleet_add,
            "list": cmd_fleet_list,
        }
        return fleet_dispatch[args.fleet_command](args)

    if args.command == "hooks":
        if getattr(args, "hooks_command", None) != "install":
            p_hooks.print_help()
            return 1
        return cmd_hooks_install(args)

    dispatch = {
        "init": cmd_init,
        "status": cmd_status,
        "new": cmd_new,
        "capture": cmd_capture,
        "recall": cmd_recall,
        "sync": cmd_sync,
        "hook": cmd_hook,
        "validate": cmd_validate,
        "lookup": cmd_lookup,
        "index": cmd_index,
        "version": cmd_version,
        "plug": cmd_plug,
        "unplug": cmd_unplug,
        "config": cmd_config,
        "migrate": cmd_migrate,
    }
    return dispatch[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
