"""Claudron CLI — knowledge engine for Claude Code."""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

from . import __version__
from .vault import (
    SCAFFOLD_TREE,
    SKIP_DIRS,
    Vault,
    VaultError,
    detect,
    init,
    scaffold_shared_tree,
    status,
)
from .knowledge import build_index, load_index, lookup


# ── vault resolution ──────────────────────────────────────────────────


def _resolve_vault(args) -> Vault:
    """Resolve vault from --vault flag, CLAUDRON_VAULT env, or walk-up."""
    vault_hint = getattr(args, "vault", None)
    if vault_hint:
        vault = detect(Path(vault_hint))
    elif os.environ.get("CLAUDRON_VAULT"):
        vault = detect(Path(os.environ["CLAUDRON_VAULT"]))
    else:
        vault = detect()

    if vault is None:
        print(
            "no vault found\n"
            "  create one:  claudron init <path>\n"
            "  or specify:  claudron --vault <path> <command>",
            file=sys.stderr,
        )
        sys.exit(2)
    return vault


# ── .claudron config ─────────────────────────────────────────────────


def _detect_claudlobby_root(hint: Path | None = None) -> Path | None:
    """Walk up from *hint* (or CWD) looking for a claudlobby repo root.

    Marker: directory containing both ``library/`` and ``lib/``.
    """
    start = (hint or Path.cwd()).resolve()
    for candidate in [start, *start.parents]:
        if (candidate / "library").is_dir() and (candidate / "lib").is_dir():
            return candidate
    return None


def _require_claudlobby_root(args, command: str) -> Path:
    """Resolve claudlobby root or exit with a clear error."""
    cl_root = _detect_claudlobby_root(_claudlobby_hint(args))
    if cl_root is None:
        print(
            f"could not find claudlobby root\n"
            f"  {command} requires a claudlobby installation\n"
            f"  specify with: claudron {command} --claudlobby <path>",
            file=sys.stderr,
        )
        sys.exit(2)
    return cl_root


def _read_claudron_config(path: Path) -> dict[str, str]:
    """Read shell-sourceable ``.claudron`` config file. Returns parsed key=value pairs."""
    result: dict[str, str] = {}
    if not path.is_file():
        return result
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, _, val = line.partition("=")
            result[key.strip()] = val.strip()
    return result


def _write_claudron_config(path: Path, vault_path: Path) -> None:
    """Write ``.claudron`` config pointing to vault."""
    path.write_text(
        f"# .claudron — auto-generated by claudron plug\nvault={vault_path}\n"
    )


# ── commands ──────────────────────────────────────────────────────────


def cmd_init(args) -> int:
    path = Path(args.path).expanduser()
    try:
        root = init(path, adopt=args.adopt)
    except VaultError as e:
        print(str(e), file=sys.stderr)
        return 2
    print(f"vault created at {root}")
    for name in SCAFFOLD_TREE:
        print(f"  _shared/{name}/")
    print("  projects/")
    return 0


def cmd_status(args) -> int:
    vault = _resolve_vault(args)
    info = status(vault, stale_days=getattr(args, "stale_days", 90))

    if args.json:
        print(json.dumps(info, indent=2))
        return 0

    print(f"vault: {info['root']}")
    print(f"docs:  {info['total_docs']}  stale: {info['total_stale']}")
    if info["fleets"]:
        print(f"fleets: {', '.join(info['fleets'])}")
    if info["projects"]:
        print(f"projects: {', '.join(info['projects'])}")
    print()
    for tier_name, tier_info in info["tiers"].items():
        if tier_info["docs"] > 0 or args.verbose:
            stale_str = f"  ({tier_info['stale']} stale)" if tier_info["stale"] else ""
            print(f"  {tier_name}: {tier_info['docs']} docs{stale_str}")

    if not info["index_present"]:
        print("\n  index: not built (will auto-build on first lookup)")
    elif not info["index_fresh"]:
        print("\n  index: stale (will auto-rebuild on next lookup)")

    for w in info["warnings"]:
        print(f"\n  warning: {w}")
    return 0


def cmd_lookup(args) -> int:
    vault = _resolve_vault(args)
    query = " ".join(args.query)
    results = lookup(
        query,
        vault,
        project=args.project,
        fleet=args.fleet,
        limit=args.limit,
        include_archived=args.include_archived,
        include_expired=args.include_expired,
    )

    if not results:
        if args.json:
            print(json.dumps({"query": query, "results": []}))
        else:
            print(f"no results for '{query}'")
        return 0

    if args.json:
        out = {
            "query": query,
            "results": [
                {
                    "title": r.doc.title,
                    "score": r.score,
                    "match_type": r.match_type,
                    "tier": r.doc.tier,
                    "path": str(r.doc.source_path.relative_to(vault.root)),
                    "tags": r.doc.tags,
                }
                for r in results
            ],
        }
        print(json.dumps(out, indent=2))
        return 0

    for r in results:
        rel = r.doc.source_path.relative_to(vault.root)
        tags = f"  [{', '.join(r.doc.tags)}]" if r.doc.tags else ""
        print(f"  [{r.score:3d}] {r.doc.title:<40s} {rel}{tags}")
    return 0


def cmd_index(args) -> int:
    vault = _resolve_vault(args)

    if not args.full:
        existing = load_index(vault)
        if existing is not None:
            count = len(existing.get("entries", []))
            print(f"index up to date ({count} entries)")
            return 0

    index = build_index(vault)
    count = len(index.get("entries", []))
    print(f"indexed {count} docs")
    return 0


def cmd_version(_args) -> int:
    print(f"claudron {__version__}")
    return 0


# ── Phase 2: claudlobby integration commands ─────────────────────────


def cmd_plug(args) -> int:
    vault_path = Path(args.vault_path).expanduser().resolve()
    if not any((vault_path / m).is_dir() for m in ("_shared", "shared")):
        print(
            f"not a vault: {vault_path} (no _shared/ or shared/ directory)",
            file=sys.stderr,
        )
        return 2

    cl_root = _require_claudlobby_root(args, "plug")

    config_path = cl_root / ".claudron"
    old_config = _read_claudron_config(config_path)
    old_vault = old_config.get("vault")
    if old_vault:
        print(f"replacing existing config (was: {old_vault})")
    _write_claudron_config(config_path, vault_path)
    print(f"plugged vault {vault_path}")
    print(f"  config: {config_path}")
    return 0


def cmd_unplug(args) -> int:
    cl_root = _require_claudlobby_root(args, "unplug")

    config_path = cl_root / ".claudron"
    if not config_path.is_file():
        print("no .claudron config to remove", file=sys.stderr)
        return 1

    config_path.unlink()
    print(f"unplugged (removed {config_path})")
    return 0


def _claudlobby_hint(args) -> Path | None:
    """Extract --claudlobby hint from args."""
    raw = getattr(args, "claudlobby", None)
    return Path(raw).resolve() if raw else None


def cmd_config(args) -> int:
    cl_root = _detect_claudlobby_root(_claudlobby_hint(args))

    info: dict = {"claudlobby_root": str(cl_root) if cl_root else None}

    vault_path = None
    if cl_root:
        config = _read_claudron_config(cl_root / ".claudron")
        vault_str = config.get("vault")
        if vault_str:
            vault_path = Path(vault_str)
            info["vault"] = str(vault_path)
            info["config_file"] = str(cl_root / ".claudron")

    if vault_path and vault_path.is_dir():
        vault = detect(vault_path)
        if vault:
            info["fleets"] = list(vault.fleets.keys())
    else:
        info["vault"] = None

    if getattr(args, "json", False):
        print(json.dumps(info, indent=2))
    else:
        print(f"claudlobby: {info['claudlobby_root'] or '(not found)'}")
        print(f"vault:      {info.get('vault') or '(not plugged)'}")
        if info.get("fleets"):
            print(f"fleets:     {', '.join(info['fleets'])}")
    return 0


_FLEET_YAML_TEMPLATE = """\
fleet:
  name: {name}
  service_prefix: com.example.{name}
  bots: {{}}
"""


_RESERVED_FLEET_NAMES = SKIP_DIRS


def cmd_fleet_add(args) -> int:
    vault = _resolve_vault(args)
    name = args.name

    if name in _RESERVED_FLEET_NAMES:
        print(
            f"'{name}' is a reserved name and cannot be used as a fleet name",
            file=sys.stderr,
        )
        return 2

    fleet_dir = vault.root / name
    if fleet_dir.exists():
        print(f"fleet directory already exists: {fleet_dir}", file=sys.stderr)
        return 2

    fleet_dir.mkdir()
    (fleet_dir / "fleet.yaml").write_text(_FLEET_YAML_TEMPLATE.format(name=name))
    scaffold_shared_tree(fleet_dir / "shared")
    (fleet_dir / ".env").write_text("# Fleet secrets — never commit\n")
    (fleet_dir / ".gitignore").write_text("runtime/\n.env\n")

    print(f"fleet '{name}' scaffolded at {fleet_dir}")
    return 0


def cmd_fleet_list(args) -> int:
    vault = _resolve_vault(args)
    if not vault.fleets:
        print("no fleets in vault")
        return 0
    for name in sorted(vault.fleets):
        print(f"  {name}")
    return 0


def cmd_migrate(args) -> int:
    import shutil

    vault = _resolve_vault(args)
    fleet_name = args.fleet
    apply = args.apply
    force = getattr(args, "force", False)

    # Find claudlobby root to locate local/<fleet>/
    cl_root = _require_claudlobby_root(args, "migrate")

    source = cl_root / "local" / fleet_name
    if not source.is_dir():
        print(f"source not found: {source}", file=sys.stderr)
        return 2

    dest = vault.root / fleet_name
    if not dest.is_dir():
        print(
            f"fleet dir not in vault: {dest}\n  run: claudron fleet add {fleet_name}",
            file=sys.stderr,
        )
        return 2

    # Determine what to copy and detect overwrites
    copyable = ("shared", "library", "voices")
    plan: list[tuple[Path, Path]] = []
    for dirname in copyable:
        src = source / dirname
        if src.is_dir():
            plan.append((src, dest / dirname))

    # Memory dirs: look in runtime/bots/*/memory/
    runtime_bots = source / "runtime" / "bots"
    memory_plan: list[tuple[Path, Path]] = []
    if runtime_bots.is_dir():
        for bot_dir in sorted(runtime_bots.iterdir()):
            mem = bot_dir / "memory"
            if mem.is_dir() and any(mem.iterdir()):
                memory_plan.append(
                    (mem, dest / "runtime" / "bots" / bot_dir.name / "memory")
                )

    if not plan and not memory_plan:
        print("nothing to migrate")
        return 0

    # Build detailed file plan, distinguish new vs overwrite
    has_overwrites = False
    for src, dst in plan + memory_plan:
        is_memory = src in [m[0] for m in memory_plan]
        for item in sorted(src.rglob("*")):
            if item.is_dir():
                continue
            rel = item.relative_to(src)
            target = dst / rel
            overwrites = target.is_file()
            if overwrites:
                has_overwrites = True
            verb = "preserve" if is_memory else "copy"
            if not apply:
                verb = "would " + verb
            tag = " (overwrite)" if overwrites else " (new)"
            print(
                f"  {verb}: {item.relative_to(cl_root)} -> {target.relative_to(vault.root)}{tag}"
            )

    if not apply:
        print("\ndry run — pass --apply to execute")
        return 0

    if has_overwrites and not force:
        print(
            "\nsome files would be overwritten — pass --force to confirm",
            file=sys.stderr,
        )
        return 1

    # Execute
    for src, dst in plan + memory_plan:
        if dst.is_dir():
            for item in src.rglob("*"):
                rel = item.relative_to(src)
                target = dst / rel
                if item.is_dir():
                    target.mkdir(parents=True, exist_ok=True)
                else:
                    target.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(item, target)
        else:
            shutil.copytree(src, dst)

    print("\nmigration complete — verify with: claudron status")
    return 0


# ── main ──────────────────────────────────────────────────────────────


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        prog="claudron",
        description="Knowledge engine for Claude Code",
    )
    parser.add_argument("--vault", help="Vault path (default: detect from CWD)")
    sub = parser.add_subparsers(dest="command")

    # init
    p_init = sub.add_parser("init", help="Scaffold a new vault")
    p_init.add_argument("path", help="Where to create the vault")
    p_init.add_argument(
        "--adopt", action="store_true", help="Adopt an existing non-empty directory"
    )

    # status
    p_status = sub.add_parser("status", help="Vault contents and health summary")
    p_status.add_argument("--json", action="store_true", help="JSON output")
    p_status.add_argument(
        "--stale-days", type=int, default=90, help="Staleness threshold in days"
    )
    p_status.add_argument(
        "-v", "--verbose", action="store_true", help="Show empty tiers"
    )

    # lookup
    p_lookup = sub.add_parser("lookup", help="Search vault knowledge")
    p_lookup.add_argument("query", nargs="+", help="Search terms")
    p_lookup.add_argument("--project", help="Project context for scoped search")
    p_lookup.add_argument("--fleet", help="Fleet context for scoped search")
    p_lookup.add_argument(
        "--limit", type=int, default=5, help="Max results (default: 5)"
    )
    p_lookup.add_argument("--json", action="store_true", help="JSON output")
    p_lookup.add_argument(
        "--include-archived",
        action="store_true",
        help="Include archived/completed docs",
    )
    p_lookup.add_argument(
        "--include-expired", action="store_true", help="Include expired docs"
    )

    # index
    p_index = sub.add_parser("index", help="Build or rebuild the Tier A index")
    p_index.add_argument(
        "--full", action="store_true", help="Force full rebuild even if fresh"
    )

    # version
    sub.add_parser("version", help="Print version")

    # plug
    p_plug = sub.add_parser("plug", help="Register vault with claudlobby")
    p_plug.add_argument("vault_path", help="Path to vault")
    p_plug.add_argument(
        "--claudlobby", default=None, help="Claudlobby root (default: auto-detect)"
    )

    # unplug
    p_unplug = sub.add_parser("unplug", help="Disconnect vault from claudlobby")
    p_unplug.add_argument(
        "--claudlobby", default=None, help="Claudlobby root (default: auto-detect)"
    )

    # config
    p_config = sub.add_parser("config", help="Show resolved config")
    p_config.add_argument("--json", action="store_true", help="JSON output")
    p_config.add_argument(
        "--claudlobby", default=None, help="Claudlobby root (default: auto-detect)"
    )

    # fleet
    p_fleet = sub.add_parser("fleet", help="Fleet overlay management")
    fleet_sub = p_fleet.add_subparsers(dest="fleet_command")

    p_fleet_add = fleet_sub.add_parser("add", help="Scaffold fleet overlay in vault")
    p_fleet_add.add_argument("name", help="Fleet name")

    fleet_sub.add_parser("list", help="List fleets in vault")

    # migrate
    p_migrate = sub.add_parser(
        "migrate", help="Migrate local/<fleet>/ to vault (dry-run default)"
    )
    p_migrate.add_argument("--fleet", required=True, help="Fleet name to migrate")
    p_migrate.add_argument(
        "--apply", action="store_true", help="Execute migration (default: dry-run)"
    )
    p_migrate.add_argument(
        "--force", action="store_true", help="Allow overwriting existing files"
    )
    p_migrate.add_argument(
        "--claudlobby", default=None, help="Claudlobby root (default: auto-detect)"
    )

    args = parser.parse_args(argv)
    if not args.command:
        parser.print_help()
        return 1

    # Handle fleet subcommands
    if args.command == "fleet":
        if not getattr(args, "fleet_command", None):
            p_fleet.print_help()
            return 1
        fleet_dispatch = {
            "add": cmd_fleet_add,
            "list": cmd_fleet_list,
        }
        return fleet_dispatch[args.fleet_command](args)

    dispatch = {
        "init": cmd_init,
        "status": cmd_status,
        "lookup": cmd_lookup,
        "index": cmd_index,
        "version": cmd_version,
        "plug": cmd_plug,
        "unplug": cmd_unplug,
        "config": cmd_config,
        "migrate": cmd_migrate,
    }
    return dispatch[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
