"""Claudron CLI — knowledge engine for Claude Code."""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

import yaml

from . import __version__
from .schema import (
    STATUS_VOCAB,
    TYPE_DIRS,
    TYPES,
    Finding,
    slugify,
    validate_path,
)
from .vault import (
    SCAFFOLD_TREE,
    SKIP_DIRS,
    Vault,
    VaultError,
    detect,
    init,
    scaffold_shared_tree,
    status,
)
from .knowledge import build_index, load_index, lookup
from .session import derive_project, recall, render_brief


# ── output contract (docs/CLI_CONTRACT.md) ────────────────────────────
#
# stdout carries payload only (session hooks inject it verbatim);
# diagnostics go to stderr. --json emits exactly one envelope on stdout.


def _envelope(command: str, data: dict, findings: list[Finding] | None = None) -> dict:
    errors = [f.to_dict() for f in findings or [] if f.severity == "error"]
    warnings = [f.to_dict() for f in findings or [] if f.severity == "warning"]
    return {
        "ok": not errors,
        "command": command,
        "data": data,
        "warnings": warnings,
        "errors": errors,
    }


def _emit_json(command: str, data: dict, findings: list[Finding] | None = None) -> None:
    print(json.dumps(_envelope(command, data, findings), indent=2, default=str))


# ── vault resolution ──────────────────────────────────────────────────


def _resolve_vault(args) -> Vault:
    """Resolve vault from --vault flag, CLAUDRON_VAULT env, or walk-up."""
    vault_hint = getattr(args, "vault", None)
    if vault_hint:
        vault = detect(Path(vault_hint))
    elif os.environ.get("CLAUDRON_VAULT"):
        vault = detect(Path(os.environ["CLAUDRON_VAULT"]))
    else:
        vault = detect()

    if vault is None:
        print(
            "no vault found\n"
            "  create one:  claudron init <path>\n"
            "  or specify:  claudron --vault <path> <command>",
            file=sys.stderr,
        )
        sys.exit(3)  # environment error (docs/CLI_CONTRACT.md; was 2 pre-0.2.0)
    return vault


# ── .claudron config ─────────────────────────────────────────────────


def _detect_claudlobby_root(hint: Path | None = None) -> Path | None:
    """Walk up from *hint* (or CWD) looking for a claudlobby repo root.

    Marker: directory containing both ``library/`` and ``lib/``.
    """
    start = (hint or Path.cwd()).resolve()
    for candidate in [start, *start.parents]:
        if (candidate / "library").is_dir() and (candidate / "lib").is_dir():
            return candidate
    return None


def _require_claudlobby_root(args, command: str) -> Path:
    """Resolve claudlobby root or exit with a clear error."""
    cl_root = _detect_claudlobby_root(_claudlobby_hint(args))
    if cl_root is None:
        print(
            f"could not find claudlobby root\n"
            f"  {command} requires a claudlobby installation\n"
            f"  specify with: claudron {command} --claudlobby <path>",
            file=sys.stderr,
        )
        sys.exit(3)  # environment error (docs/CLI_CONTRACT.md; was 2 pre-0.2.0)
    return cl_root


def _read_claudron_config(path: Path) -> dict[str, str]:
    """Read shell-sourceable ``.claudron`` config file. Returns parsed key=value pairs."""
    result: dict[str, str] = {}
    if not path.is_file():
        return result
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, _, val = line.partition("=")
            result[key.strip()] = val.strip()
    return result


def _write_claudron_config(path: Path, vault_path: Path) -> None:
    """Write ``.claudron`` config pointing to vault."""
    path.write_text(
        f"# .claudron — auto-generated by claudron plug\nvault={vault_path}\n"
    )


# ── commands ──────────────────────────────────────────────────────────


def cmd_init(args) -> int:
    path = Path(args.path).expanduser()
    try:
        root = init(path, adopt=args.adopt)
    except VaultError as e:
        print(str(e), file=sys.stderr)
        return 2
    if args.json:
        _emit_json(
            "init",
            {"root": str(root), "scaffold": [f"_shared/{n}" for n in SCAFFOLD_TREE]},
        )
        return 0
    print(f"vault created at {root}")
    for name in SCAFFOLD_TREE:
        print(f"  _shared/{name}/")
    print("  projects/")
    return 0


def cmd_status(args) -> int:
    vault = _resolve_vault(args)
    info = status(vault, stale_days=getattr(args, "stale_days", 90))

    if args.json:
        _emit_json("status", info)
        return 0

    print(f"vault: {info['root']}")
    print(f"docs:  {info['total_docs']}  stale: {info['total_stale']}")
    if info["fleets"]:
        print(f"fleets: {', '.join(info['fleets'])}")
    if info["projects"]:
        print(f"projects: {', '.join(info['projects'])}")
    print()
    for tier_name, tier_info in info["tiers"].items():
        if tier_info["docs"] > 0 or args.verbose:
            stale_str = f"  ({tier_info['stale']} stale)" if tier_info["stale"] else ""
            print(f"  {tier_name}: {tier_info['docs']} docs{stale_str}")

    # Index state + vault warnings are diagnostics, not payload → stderr
    if not info["index_present"]:
        print("index: not built (will auto-build on first lookup)", file=sys.stderr)
    elif not info["index_fresh"]:
        print("index: stale (will auto-rebuild on next lookup)", file=sys.stderr)
    for w in info["warnings"]:
        print(f"warning: {w}", file=sys.stderr)
    return 0


def cmd_lookup(args) -> int:
    vault = _resolve_vault(args)
    query = " ".join(args.query)
    results = lookup(
        query,
        vault,
        project=args.project,
        fleet=args.fleet,
        limit=args.limit,
        include_archived=args.include_archived,
        include_expired=args.include_expired,
    )

    if not results:
        if args.json:
            _emit_json("lookup", {"query": query, "results": []})
        else:
            print(f"no results for '{query}'", file=sys.stderr)
        return 0

    if args.json:
        _emit_json(
            "lookup",
            {
                "query": query,
                "results": [
                    {
                        "title": r.doc.title,
                        "score": r.score,
                        "match_type": r.match_type,
                        "tier": r.doc.tier,
                        "path": str(r.doc.source_path.relative_to(vault.root)),
                        "tags": r.doc.tags,
                    }
                    for r in results
                ],
            },
        )
        return 0

    for r in results:
        rel = r.doc.source_path.relative_to(vault.root)
        tags = f"  [{', '.join(r.doc.tags)}]" if r.doc.tags else ""
        print(f"  [{r.score:3d}] {r.doc.title:<40s} {rel}{tags}")
    return 0


def cmd_index(args) -> int:
    vault = _resolve_vault(args)

    existing = None if args.full else load_index(vault)
    if existing is not None:
        count, rebuilt = len(existing.get("entries", [])), False
        msg = f"index up to date ({count} entries)"
    else:
        count, rebuilt = len(build_index(vault).get("entries", [])), True
        msg = f"indexed {count} docs"

    if args.json:
        _emit_json("index", {"entries": count, "rebuilt": rebuilt})
    else:
        print(msg, file=sys.stderr)
    return 0


def cmd_version(args) -> int:
    if args.json:
        _emit_json("version", {"version": __version__})
    else:
        print(f"claudron {__version__}")
    return 0


def _derive_owner(args) -> str:
    """--owner → git config user.name → $USER (docs/CLI_CONTRACT.md)."""
    if getattr(args, "owner", None):
        return args.owner
    import subprocess

    try:
        name = subprocess.run(
            ["git", "config", "user.name"], capture_output=True, text=True, timeout=5
        ).stdout.strip()
        if name:
            return name
    except (OSError, subprocess.TimeoutExpired):
        # TimeoutExpired is a SubprocessError, NOT an OSError — without
        # naming it, the timeout guard guards nothing (review minor 6).
        pass
    return os.environ.get("USER", "unknown")


def _yaml_scalar(value: str) -> str:
    """Quote a string for hand-assembled frontmatter unless it round-trips
    through the real YAML parser as the identical string. Character lists
    are not enough — implicit typing turns bare `true`/`0`/`2026-07-08`
    into bool/int/date (review: a bool title crashed lookup vault-wide).
    json.dumps output is valid double-quoted YAML."""
    if value != value.strip():
        return json.dumps(value)
    try:
        parsed = yaml.safe_load(value)
    except yaml.YAMLError:
        return json.dumps(value)
    if isinstance(parsed, str) and parsed == value:
        return value
    return json.dumps(value)


def cmd_new(args) -> int:
    from datetime import date

    vault = _resolve_vault(args)
    title = args.title
    note_type = args.type

    if args.project:
        # Projects file flat (projects/<name>/ is one tier, not a tiered
        # tree); TYPE_DIRS applies only inside shared trees.
        base = vault.root / "projects" / args.project
    elif args.fleet:
        if args.fleet not in vault.fleets:
            # Writing into an unregistered overlay creates untracked
            # content and forecloses `fleet add` (review major 4).
            print(
                f"fleet not in vault: {args.fleet}\n"
                f"  run: claudron fleet add {args.fleet}",
                file=sys.stderr,
            )
            return 2
        base = vault.fleets[args.fleet] / "shared" / TYPE_DIRS[note_type]
    else:
        base = vault.shared / TYPE_DIRS[note_type]

    # Containment: scope names are agent-derived input; ../ must never
    # write outside the vault (review blocker 3 — arbitrary-file-write).
    base = base.resolve()
    if not base.is_relative_to(vault.root.resolve()):
        scope = args.project or args.fleet
        print(f"scope {scope!r} escapes the vault root", file=sys.stderr)
        return 2
    base.mkdir(parents=True, exist_ok=True)

    target = base / f"{slugify(title)}.md"
    if target.exists() and not args.force:
        print(
            f"note already exists: {target}\n  pass --force to overwrite",
            file=sys.stderr,
        )
        return 1

    # Hand-assembled rather than yaml.dump — pins key order, flow-style
    # tags, and unquoted ISO dates so the note stays human-shaped.
    # _yaml_scalar covers the escaping this trades away.
    fm_lines = [
        "---",
        f"title: {_yaml_scalar(title)}",
        f"type: {note_type}",
        f"status: {STATUS_VOCAB[note_type]['default']}",
        f"owner: {_yaml_scalar(_derive_owner(args))}",
    ]
    if args.tags:
        # List-encoded, never hand-joined — "todo #urgent" / "foo]bar"
        # produced unparseable notes (review blocker 2). json.dumps of a
        # str list is a valid YAML flow sequence.
        fm_lines.append(f"tags: {json.dumps([t.strip() for t in args.tags.split(',')])}")
    today = date.today().isoformat()
    fm_lines += [f"created: {today}", f"updated: {today}", "schema_version: 1", "---"]
    target.write_text("\n".join(fm_lines) + f"\n\n# {title}\n")

    if args.edit:
        editor = os.environ.get("EDITOR")
        if editor:
            import subprocess

            subprocess.run([editor, str(target)])
        else:
            print("$EDITOR is not set — note written, not opened", file=sys.stderr)

    if args.json:
        _emit_json("new", {"path": str(target)})
    else:
        print(str(target))
    return 0


def cmd_recall(args) -> int:
    vault = _resolve_vault(args)
    # A derived name with no matching project tier still contributes as
    # the shared-tier relevance term — recall() handles both roles.
    project = args.project or derive_project()
    query = " ".join(args.query) if args.query else None
    data = recall(vault, project=project, query=query, limit=args.limit)

    if args.json:
        _emit_json("recall", data)
        return 0

    brief = render_brief(data)
    if brief:
        print(brief)
    else:
        # Abstention: inject nothing rather than something (stderr only).
        print("no context recalled", file=sys.stderr)
    return 0


def cmd_validate(args) -> int:
    strict = args.strict
    if args.path:
        target = Path(args.path).expanduser().resolve()
        if not target.exists():
            print(f"no such path: {target}", file=sys.stderr)
            return 2
        # Vault context (for relative paths + shared-root rules) when the
        # target sits inside one; otherwise the target anchors itself.
        # Note: an explicit PATH anchors to its own vault — --vault is
        # deliberately not consulted here.
        probe = target if target.is_dir() else target.parent
        anchor = detect(probe)
        findings = validate_path(
            target, strict=strict, vault_root=anchor.root if anchor else probe
        )
    else:
        vault = _resolve_vault(args)
        findings = validate_path(vault.root, strict=strict, vault_root=vault.root)

    errors = [f for f in findings if f.severity == "error"]
    warnings = [f for f in findings if f.severity == "warning"]

    if args.json:
        _emit_json(
            "validate",
            {"errors": len(errors), "warnings": len(warnings), "strict": strict},
            findings,
        )
        return 1 if errors else 0

    for f in findings:
        loc = f.path + (f":{f.line}" if f.line else "")
        print(f"[{f.code}] {f.severity} {loc} — {f.message}")
    print(
        f"{len(errors)} error(s), {len(warnings)} warning(s)"
        + (" [strict]" if strict else ""),
        file=sys.stderr,
    )
    return 1 if errors else 0


# ── Phase 2: claudlobby integration commands ─────────────────────────


def cmd_plug(args) -> int:
    vault_path = Path(args.vault_path).expanduser().resolve()
    if not any((vault_path / m).is_dir() for m in ("_shared", "shared")):
        print(
            f"not a vault: {vault_path} (no _shared/ or shared/ directory)",
            file=sys.stderr,
        )
        return 2

    cl_root = _require_claudlobby_root(args, "plug")

    config_path = cl_root / ".claudron"
    old_config = _read_claudron_config(config_path)
    old_vault = old_config.get("vault")
    if old_vault:
        print(f"replacing existing config (was: {old_vault})")
    _write_claudron_config(config_path, vault_path)
    print(f"plugged vault {vault_path}")
    print(f"  config: {config_path}")
    return 0


def cmd_unplug(args) -> int:
    cl_root = _require_claudlobby_root(args, "unplug")

    config_path = cl_root / ".claudron"
    if not config_path.is_file():
        print("no .claudron config to remove", file=sys.stderr)
        return 1

    config_path.unlink()
    print(f"unplugged (removed {config_path})")
    return 0


def _claudlobby_hint(args) -> Path | None:
    """Extract --claudlobby hint from args."""
    raw = getattr(args, "claudlobby", None)
    return Path(raw).resolve() if raw else None


def cmd_config(args) -> int:
    cl_root = _detect_claudlobby_root(_claudlobby_hint(args))

    info: dict = {"claudlobby_root": str(cl_root) if cl_root else None}

    vault_path = None
    if cl_root:
        config = _read_claudron_config(cl_root / ".claudron")
        vault_str = config.get("vault")
        if vault_str:
            vault_path = Path(vault_str)
            info["vault"] = str(vault_path)
            info["config_file"] = str(cl_root / ".claudron")

    if vault_path and vault_path.is_dir():
        vault = detect(vault_path)
        if vault:
            info["fleets"] = list(vault.fleets.keys())
    else:
        info["vault"] = None

    if args.json:
        _emit_json("config", info)
    else:
        print(f"claudlobby: {info['claudlobby_root'] or '(not found)'}")
        print(f"vault:      {info.get('vault') or '(not plugged)'}")
        if info.get("fleets"):
            print(f"fleets:     {', '.join(info['fleets'])}")
    return 0


_FLEET_YAML_TEMPLATE = """\
fleet:
  name: {name}
  service_prefix: com.example.{name}
  bots: {{}}
"""


_RESERVED_FLEET_NAMES = SKIP_DIRS


def cmd_fleet_add(args) -> int:
    vault = _resolve_vault(args)
    name = args.name

    if name in _RESERVED_FLEET_NAMES:
        print(
            f"'{name}' is a reserved name and cannot be used as a fleet name",
            file=sys.stderr,
        )
        return 2

    fleet_dir = vault.root / name
    if fleet_dir.exists():
        print(f"fleet directory already exists: {fleet_dir}", file=sys.stderr)
        return 2

    fleet_dir.mkdir()
    (fleet_dir / "fleet.yaml").write_text(_FLEET_YAML_TEMPLATE.format(name=name))
    scaffold_shared_tree(fleet_dir / "shared")
    (fleet_dir / ".env").write_text("# Fleet secrets — never commit\n")
    (fleet_dir / ".gitignore").write_text("runtime/\n.env\n")

    print(f"fleet '{name}' scaffolded at {fleet_dir}")
    return 0


def cmd_fleet_list(args) -> int:
    vault = _resolve_vault(args)
    if not vault.fleets:
        print("no fleets in vault")
        return 0
    for name in sorted(vault.fleets):
        print(f"  {name}")
    return 0


def cmd_migrate(args) -> int:
    import shutil

    vault = _resolve_vault(args)
    fleet_name = args.fleet
    apply = args.apply
    force = getattr(args, "force", False)

    # Find claudlobby root to locate local/<fleet>/
    cl_root = _require_claudlobby_root(args, "migrate")

    source = cl_root / "local" / fleet_name
    if not source.is_dir():
        print(f"source not found: {source}", file=sys.stderr)
        return 2

    dest = vault.root / fleet_name
    if not dest.is_dir():
        print(
            f"fleet dir not in vault: {dest}\n  run: claudron fleet add {fleet_name}",
            file=sys.stderr,
        )
        return 2

    # Determine what to copy and detect overwrites
    copyable = ("shared", "library", "voices")
    plan: list[tuple[Path, Path]] = []
    for dirname in copyable:
        src = source / dirname
        if src.is_dir():
            plan.append((src, dest / dirname))

    # Memory dirs: look in runtime/bots/*/memory/
    runtime_bots = source / "runtime" / "bots"
    memory_plan: list[tuple[Path, Path]] = []
    if runtime_bots.is_dir():
        for bot_dir in sorted(runtime_bots.iterdir()):
            mem = bot_dir / "memory"
            if mem.is_dir() and any(mem.iterdir()):
                memory_plan.append(
                    (mem, dest / "runtime" / "bots" / bot_dir.name / "memory")
                )

    if not plan and not memory_plan:
        print("nothing to migrate")
        return 0

    # Build detailed file plan, distinguish new vs overwrite
    has_overwrites = False
    for src, dst in plan + memory_plan:
        is_memory = src in [m[0] for m in memory_plan]
        for item in sorted(src.rglob("*")):
            if item.is_dir():
                continue
            rel = item.relative_to(src)
            target = dst / rel
            overwrites = target.is_file()
            if overwrites:
                has_overwrites = True
            verb = "preserve" if is_memory else "copy"
            if not apply:
                verb = "would " + verb
            tag = " (overwrite)" if overwrites else " (new)"
            print(
                f"  {verb}: {item.relative_to(cl_root)} -> {target.relative_to(vault.root)}{tag}"
            )

    if not apply:
        print("\ndry run — pass --apply to execute")
        return 0

    if has_overwrites and not force:
        print(
            "\nsome files would be overwritten — pass --force to confirm",
            file=sys.stderr,
        )
        return 1

    # Execute
    for src, dst in plan + memory_plan:
        if dst.is_dir():
            for item in src.rglob("*"):
                rel = item.relative_to(src)
                target = dst / rel
                if item.is_dir():
                    target.mkdir(parents=True, exist_ok=True)
                else:
                    target.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(item, target)
        else:
            shutil.copytree(src, dst)

    print("\nmigration complete — verify with: claudron status")
    return 0


# ── main ──────────────────────────────────────────────────────────────


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        prog="claudron",
        description="Knowledge engine for Claude Code",
    )
    parser.add_argument("--vault", help="Vault path (default: detect from CWD)")
    sub = parser.add_subparsers(dest="command")

    # Shared parents (docs/CLI_CONTRACT.md): --vault/--json on subcommands
    # too, so `claudron status --json` and `claudron status --vault X` both
    # parse. Argparse only applies a subparser default when the attribute
    # is absent, so the top-level --vault value survives.
    # SUPPRESS is load-bearing: Python 3.14 argparse applies subparser
    # defaults over values the top-level parser already set, so a plain
    # default=None here would null out `claudron --vault X status`.
    vault_parent = argparse.ArgumentParser(add_help=False)
    vault_parent.add_argument(
        "--vault",
        default=argparse.SUPPRESS,
        help="Vault path (default: detect from CWD)",
    )
    json_parent = argparse.ArgumentParser(add_help=False)
    json_parent.add_argument(
        "--json", action="store_true", help="Emit the standard JSON envelope"
    )

    # init
    p_init = sub.add_parser(
        "init", help="Scaffold a new vault", parents=[json_parent]
    )
    p_init.add_argument("path", help="Where to create the vault")
    p_init.add_argument(
        "--adopt", action="store_true", help="Adopt an existing non-empty directory"
    )

    # status
    p_status = sub.add_parser(
        "status",
        help="Vault contents and health summary",
        parents=[vault_parent, json_parent],
    )
    p_status.add_argument(
        "--stale-days", type=int, default=90, help="Staleness threshold in days"
    )
    p_status.add_argument(
        "-v", "--verbose", action="store_true", help="Show empty tiers"
    )

    # validate
    p_validate = sub.add_parser(
        "validate",
        help="Lint notes against SCHEMA.md (never mutates)",
        parents=[vault_parent, json_parent],
    )
    p_validate.add_argument(
        "path",
        nargs="?",
        default=None,
        help="File or directory (default: the detected vault)",
    )
    p_validate.add_argument(
        "--strict",
        action="store_true",
        help="Authoring tier — what the engine/bot write paths enforce",
    )

    # new
    p_new = sub.add_parser(
        "new",
        help="Scaffold a schema-valid note (passes validate --strict)",
        parents=[vault_parent, json_parent],
    )
    p_new.add_argument("type", choices=TYPES, help="Note type")
    p_new.add_argument("title", help="Note title")
    scope = p_new.add_mutually_exclusive_group()
    scope.add_argument("--project", help="File under projects/<name>/")
    scope.add_argument("--fleet", help="File under <fleet>/shared/")
    p_new.add_argument("--tags", help="Comma-separated tags")
    p_new.add_argument("--owner", help="Owner (default: git user.name, then $USER)")
    p_new.add_argument("--edit", action="store_true", help="Open in $EDITOR")
    p_new.add_argument(
        "--force", action="store_true", help="Overwrite an existing note"
    )

    # recall
    p_recall = sub.add_parser(
        "recall",
        help="Session-start context brief (stdout is the injectable payload)",
        parents=[vault_parent, json_parent],
    )
    p_recall.add_argument(
        "--project", help="Project scope (default: derive from cwd git root)"
    )
    p_recall.add_argument(
        "--query", nargs="*", help="Relevance terms (default: the project name)"
    )
    p_recall.add_argument(
        "--limit", type=int, default=5, help="Notes per tier (default: 5)"
    )

    # lookup
    p_lookup = sub.add_parser(
        "lookup", help="Search vault knowledge", parents=[vault_parent, json_parent]
    )
    p_lookup.add_argument("query", nargs="+", help="Search terms")
    p_lookup.add_argument("--project", help="Project context for scoped search")
    p_lookup.add_argument("--fleet", help="Fleet context for scoped search")
    p_lookup.add_argument(
        "--limit", type=int, default=5, help="Max results (default: 5)"
    )
    p_lookup.add_argument(
        "--include-archived",
        action="store_true",
        help="Include archived/completed docs",
    )
    p_lookup.add_argument(
        "--include-expired", action="store_true", help="Include expired docs"
    )

    # index
    p_index = sub.add_parser(
        "index",
        help="Build or rebuild the frontmatter index",
        parents=[vault_parent, json_parent],
    )
    p_index.add_argument(
        "--full", action="store_true", help="Force full rebuild even if fresh"
    )

    # version
    sub.add_parser("version", help="Print version", parents=[json_parent])

    # plug
    p_plug = sub.add_parser("plug", help="Register vault with claudlobby")
    p_plug.add_argument("vault_path", help="Path to vault")
    p_plug.add_argument(
        "--claudlobby", default=None, help="Claudlobby root (default: auto-detect)"
    )

    # unplug
    p_unplug = sub.add_parser("unplug", help="Disconnect vault from claudlobby")
    p_unplug.add_argument(
        "--claudlobby", default=None, help="Claudlobby root (default: auto-detect)"
    )

    # config
    p_config = sub.add_parser(
        "config", help="Show resolved config", parents=[json_parent]
    )
    p_config.add_argument(
        "--claudlobby", default=None, help="Claudlobby root (default: auto-detect)"
    )

    # fleet
    p_fleet = sub.add_parser("fleet", help="Fleet overlay management")
    fleet_sub = p_fleet.add_subparsers(dest="fleet_command")

    p_fleet_add = fleet_sub.add_parser("add", help="Scaffold fleet overlay in vault")
    p_fleet_add.add_argument("name", help="Fleet name")

    fleet_sub.add_parser("list", help="List fleets in vault")

    # migrate
    p_migrate = sub.add_parser(
        "migrate", help="Migrate local/<fleet>/ to vault (dry-run default)"
    )
    p_migrate.add_argument("--fleet", required=True, help="Fleet name to migrate")
    p_migrate.add_argument(
        "--apply", action="store_true", help="Execute migration (default: dry-run)"
    )
    p_migrate.add_argument(
        "--force", action="store_true", help="Allow overwriting existing files"
    )
    p_migrate.add_argument(
        "--claudlobby", default=None, help="Claudlobby root (default: auto-detect)"
    )

    args = parser.parse_args(argv)
    if not args.command:
        parser.print_help()
        return 1

    # Handle fleet subcommands
    if args.command == "fleet":
        if not getattr(args, "fleet_command", None):
            p_fleet.print_help()
            return 1
        fleet_dispatch = {
            "add": cmd_fleet_add,
            "list": cmd_fleet_list,
        }
        return fleet_dispatch[args.fleet_command](args)

    dispatch = {
        "init": cmd_init,
        "status": cmd_status,
        "new": cmd_new,
        "recall": cmd_recall,
        "validate": cmd_validate,
        "lookup": cmd_lookup,
        "index": cmd_index,
        "version": cmd_version,
        "plug": cmd_plug,
        "unplug": cmd_unplug,
        "config": cmd_config,
        "migrate": cmd_migrate,
    }
    return dispatch[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
