"""`INDEX.md` as a DERIVED navigation file (#155).

A hand-maintained per-directory list that every host and every bot appends to
is the most conflict-prone file in a vault. Repairing the 2026-09-21 outage
produced nine merge conflicts and six were `INDEX.md`, every one resolved by
the same mechanical union of entries -- and the same entry carried DIFFERENT
DESCRIPTION TEXT in different versions, so no line-based merge could have
resolved any of them. Generating the file removes the class: a derived artifact
is regenerated, never merged.

THE RULING THIS MODULE IS BUILT AROUND, and the reason it is not a comment:

  **A generator that drops what it does not know about is a silent deletion.**

Existing `INDEX.md` files carry hand-written entries and hand-written
descriptions, and a vault whose entire purpose is durable knowledge is the
worst possible place to lose prose with no diff anyone reads. So an entry in
the file that the index does not have is not simply overwritten. It is split on
an OBSERVABLE fact rather than on one blanket policy, because the two halves
have opposite correct answers:

  * **The target file EXISTS** -- the entry points at something real that the
    index does not cover (a README, a subdirectory, a note the index has not
    caught up with, a hand-authored pointer). Its text is knowledge somebody
    wrote. It is **PRESERVED** verbatim under a marked section, and reported.
  * **The target file DOES NOT EXIST** -- the entry is dangling. There is
    nothing to navigate to, and keeping it is worse than dropping it. It is
    **DROPPED**, and reported.

Neither half is silent. `NavigationResult` carries both lists, and both are
named in the bound the caller prints.

Preserving rather than refusing is deliberate. This door is meant to run on
every capture (#155 PR 2), and a door that refuses the whole regeneration
because one directory holds one odd line would be turned off within a week --
at which point every `INDEX.md` is hand-edited again and the conflict class is
back. Refusal protects the file; being switched off protects nothing.

VERSION. `NAVIGATION_ENGINE_VERSION` is an INTERFACE, not a nicety: Claudlobby
#1723 is blocked on this door and gates on the engine version that ships it, so
a consumer can ask whether the door it needs is present rather than guessing
from a release tag.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:  # pragma: no cover
    from .vault import Vault

#: The interface Claudlobby #1723 gates on. Bump when the RENDERED FORMAT or the
#: preserve/drop ruling changes -- not for internal refactors, since a consumer
#: asking "is the door I need here" is asking about those two things only.
NAVIGATION_ENGINE_VERSION = "1"

#: On every generated file. Its absence is what `validate` warns about, and what
#: tells a human the file is not theirs to edit.
HEADER = "<!-- generated by claudron index --navigation; do not hand-edit -->"

#: Where preserved entries go. Marked, so the next reader can see that this part
#: is NOT derived and why -- an unmarked preserved line would read as generated
#: and quietly become untrustworthy.
PRESERVED_HEADING = "## Not derived from the index"
PRESERVED_NOTE = (
    "These entries were in this file and are not in the index, but their target "
    "exists. They are kept verbatim rather than dropped -- see "
    "`claudron/navigation.py`. Remove the target or index it to resolve."
)

#: `- [Title](target)` -- the link is what an entry is KEYED on. The outage's
#: six conflicts were all resolved by keying on link target and taking the
#: union, so that is the key here too.
_ENTRY_RE = re.compile(r"^\s*[-*]\s*\[(?P<title>[^\]]*)\]\((?P<target>[^)]+)\)")


@dataclass
class NavigationResult:
    """What was written, and everything it could not simply derive.

    #1742's rule applies to this door as much as to any read door: a caller
    must be able to say what it generated from, what it skipped, and what it
    could not resolve, without reading the source."""

    written: list[Path] = field(default_factory=list)
    unchanged: list[Path] = field(default_factory=list)
    preserved: dict[str, list[str]] = field(default_factory=dict)
    dropped: dict[str, list[str]] = field(default_factory=dict)
    skipped: dict[str, str] = field(default_factory=dict)
    entries_seen: int = 0
    directories_considered: int = 0
    engine_version: str = NAVIGATION_ENGINE_VERSION

    def bound_lines(self) -> list[str]:
        n_pres = sum(len(v) for v in self.preserved.values())
        n_drop = sum(len(v) for v in self.dropped.values())
        lines = [
            f"GENERATED FROM: the index ({self.entries_seen} entry(ies)) — the "
            "notes' own frontmatter, never the previous file's text",
            f"DIRECTORIES   : {self.directories_considered} considered, "
            f"{len(self.written)} written, {len(self.unchanged)} already current",
        ]
        if self.skipped:
            lines.append(f"SKIPPED       : {len(self.skipped)} — "
                         + "; ".join(f"{k}: {v}" for k, v in
                                     sorted(self.skipped.items())[:3])
                         + (" …" if len(self.skipped) > 3 else ""))
        lines.append(
            f"NOT DERIVED   : {n_pres} entry(ies) PRESERVED (in the file, not in "
            f"the index, target exists) · {n_drop} DROPPED (target missing)")
        if n_pres or n_drop:
            for path, kept in sorted(self.preserved.items()):
                lines.append(f"  preserved in {path}: {', '.join(kept)}")
            for path, gone in sorted(self.dropped.items()):
                lines.append(f"  dropped from {path}: {', '.join(gone)}")
        else:
            lines.append("                nothing in any file was unaccounted for")
        return lines


def _fmt_entry(e: dict) -> str:
    """The fleet protocol's exact line (Claudlobby
    `library/protocols/shared-documentation.md`):

        - [Title](file.md) — description (status: X, owner: Y, tags: a, b)

    An empty field is OMITTED rather than rendered blank -- `(status: , owner: )`
    is noise a reader has to parse past, and the protocol's readers key on the
    labels rather than on position."""
    title = e.get("title") or e.get("filename") or "untitled"
    target = f"{e.get('filename', '')}.md"
    line = f"- [{title}]({target})"
    desc = (e.get("description") or "").strip()
    if desc:
        line += f" — {desc}"
    bits = []
    if e.get("status"):
        bits.append(f"status: {e['status']}")
    if e.get("owner"):
        bits.append(f"owner: {e['owner']}")
    tags = e.get("tags") or []
    if tags:
        bits.append("tags: " + ", ".join(tags))
    if bits:
        line += " (" + ", ".join(bits) + ")"
    return line


def _entries_for(index: dict, vault_root: Path, directory: Path) -> list[dict]:
    """Index entries whose note sits DIRECTLY inside `directory`."""
    out = []
    for e in index.get("entries", []):
        raw = e.get("path")
        if not raw:
            continue
        try:
            parent = (vault_root / raw).parent.resolve()
        except (OSError, ValueError):
            continue
        if parent == directory.resolve():
            out.append(e)
    # Deterministic: newest first, then title -- ordering churn is itself a
    # diff nobody wants to read.
    return sorted(out, key=lambda e: (str(e.get("updated", "")), str(e.get("title", ""))),
                  reverse=True)


def classify_existing(existing_text: str, directory: Path,
                      known_targets: set[str]) -> tuple[list[str], list[str]]:
    """Split the file's current entries into (preserve, drop).

    The ruling, and the whole reason this function is separate and tested: an
    entry the index does not know about is NEVER silently discarded. Whether it
    survives turns on one observable fact -- does its target exist on disk --
    because that is what decides whether there is anything left to navigate to.
    """
    preserve: list[str] = []
    drop: list[str] = []
    for raw in existing_text.splitlines():
        m = _ENTRY_RE.match(raw)
        if not m:
            continue
        target = m.group("target").strip()
        if target in known_targets:
            continue                      # derived afresh; nothing to preserve
        if (directory / target).exists():
            preserve.append(raw.rstrip())
        else:
            drop.append(f"[{m.group('title')}]({target})")
    return preserve, drop


def render_navigation(vault: "Vault", directory: Path, index: dict,
                      *, existing_text: str = "") -> tuple[str, list[str], list[str]]:
    """`(text, preserved, dropped)` for one directory — a PURE function of the
    index plus whatever the existing file holds that the index does not."""
    entries = _entries_for(index, Path(vault.root), directory)
    known = {f"{e.get('filename', '')}.md" for e in entries}
    preserved, dropped = classify_existing(existing_text, directory, known)

    lines = [HEADER, "", f"# Index: {directory.name}", ""]
    lines.extend(_fmt_entry(e) for e in entries)
    if not entries:
        lines.append("_No indexed notes in this directory._")
    if preserved:
        lines.extend(["", PRESERVED_HEADING, "", PRESERVED_NOTE, ""])
        lines.extend(preserved)
    return "\n".join(lines).rstrip() + "\n", preserved, dropped


def _candidate_directories(vault: "Vault", index: dict) -> list[Path]:
    """Every directory the index actually has a note in, plus any that already
    carries an `INDEX.md`.

    The second half matters and is not redundant: a directory whose notes have
    all been deleted still has a stale `INDEX.md` full of dangling entries, and
    a walk driven by the index alone would never visit it -- leaving the worst
    files untouched precisely because they are the emptiest."""
    root = Path(vault.root)
    dirs: set[Path] = set()
    for e in index.get("entries", []):
        raw = e.get("path")
        if raw:
            dirs.add((root / raw).parent)
    for existing in root.rglob("INDEX.md"):
        if ".claudron" not in existing.parts:
            dirs.add(existing.parent)
    return sorted(dirs)


def write_navigation(vault: "Vault", *, directories=None,
                     index: dict | None = None) -> NavigationResult:
    """Regenerate `INDEX.md` for each directory. Idempotent: unchanged content
    is not rewritten, so running twice changes nothing and a no-op costs no
    commit.

    Takes `vault_write_lock` ONCE around the whole sweep rather than per file:
    the caller's mental model is "the navigation is now correct", and a sweep
    that another writer can interleave with delivers half of that.
    """
    from .knowledge import build_index, load_index
    from .locking import atomic_write_text, vault_write_lock

    if index is None:
        index = load_index(vault) or build_index(vault)
    result = NavigationResult(entries_seen=len(index.get("entries", [])))

    with vault_write_lock(vault):
        targets = ([Path(d) for d in directories]
                   if directories is not None else _candidate_directories(vault, index))
        result.directories_considered = len(targets)
        for directory in targets:
            rel = _rel(vault, directory)
            if not directory.is_dir():
                result.skipped[rel] = "not a directory"
                continue
            path = directory / "INDEX.md"
            try:
                existing = path.read_text() if path.exists() else ""
            except OSError as exc:
                # UNREADABLE IS NOT EMPTY: treating it as empty would discard
                # every hand-written entry in it, which is the exact harm the
                # preserve ruling exists to prevent.
                result.skipped[rel] = f"existing INDEX.md unreadable ({exc.__class__.__name__})"
                continue
            text, preserved, dropped = render_navigation(
                vault, directory, index, existing_text=existing)
            if preserved:
                result.preserved[rel] = preserved
            if dropped:
                result.dropped[rel] = dropped
            if existing == text:
                result.unchanged.append(path)
                continue
            try:
                atomic_write_text(path, text)
            except OSError as exc:
                result.skipped[rel] = f"write failed ({exc.__class__.__name__})"
                continue
            result.written.append(path)
    return result


def _rel(vault: "Vault", directory: Path) -> str:
    try:
        return str(directory.relative_to(Path(vault.root)))
    except ValueError:
        return str(directory)
