"""`INDEX.md` as a DERIVED navigation file (#155).

A hand-maintained per-directory list that every host and every bot appends to
is the most conflict-prone file in a vault. Repairing the 2026-09-21 outage
produced nine merge conflicts and six were `INDEX.md`, every one resolved by
the same mechanical union of entries -- and the same entry carried DIFFERENT
DESCRIPTION TEXT in different versions, so no line-based merge could have
resolved any of them. Generating the file removes the class: a derived artifact
is regenerated, never merged.

THE RULING THIS MODULE IS BUILT AROUND, and the reason it is not a comment:

  **A generator that drops what it does not know about is a silent deletion.**

Existing `INDEX.md` files carry hand-written entries and hand-written
descriptions, and a vault whose entire purpose is durable knowledge is the
worst possible place to lose prose with no diff anyone reads. So an entry in
the file that the index does not have is not simply overwritten. It is split on
an OBSERVABLE fact rather than on one blanket policy, because the two halves
have opposite correct answers:

  * **The target file EXISTS** -- the entry points at something real that the
    index does not cover (a README, a subdirectory, a note the index has not
    caught up with, a hand-authored pointer). Its text is knowledge somebody
    wrote. It is **PRESERVED** verbatim under a marked section, and reported.
  * **The target file DOES NOT EXIST** -- the entry is dangling. There is
    nothing to navigate to, and keeping it is worse than dropping it. It is
    **DROPPED**, and reported.

Neither half is silent. `NavigationResult` carries both lists, and both are
named in the bound the caller prints.

Preserving rather than refusing is deliberate. This door is meant to run on
every capture (#155 PR 2), and a door that refuses the whole regeneration
because one directory holds one odd line would be turned off within a week --
at which point every `INDEX.md` is hand-edited again and the conflict class is
back. Refusal protects the file; being switched off protects nothing.

DETECTION. A consumer asks for this door by NAME, never by version:
`"navigation" in status --json -> data.capabilities` (`claudron.CAPABILITIES`;
`docs/CLI_CONTRACT.md` "Capability probe"). That is register rule R5 --
capability is declared to the owner, never inferred -- and it is the only form
that works here. There is deliberately no version constant in this file either:
a private version beside the sanctioned one only makes a consumer guess which
to read.

The three inferences a reader will reach for instead all fail, measured, and
the reasons are mechanical rather than stylistic:

* A VERSION FLOOR cannot be expressed. `engine_version` is `0.5.0.dev0` on a
  build of this branch and `0.4.0` on the last release; PEP 440 sorts a dev
  release BEFORE its release, so a `>= 0.5.0` floor is satisfied by neither and
  can never pass.
* A VERB probe (`claudron <verb> --help`, exit 2 on an unknown verb) cannot see
  a new FLAG on a verb that already exists.
* A FLAG probe (`claudron index --navigation --help`) cannot fail: argparse
  fires `--help` as a parse action and exits 0 before reporting unknown
  arguments, so it exits 0 on claudron 0.4.0, whose `index --help` contains no
  "navigation". Control: the same engine exits 2 for `index --navigation`
  without `--help`.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:  # pragma: no cover
    from .vault import Vault

#: Never descended when sweeping a tier for a stale `INDEX.md`. A tier may be a
#: git checkout (`projects/<repo>`), and `rglob` walks dotdirs.
_SKIP_PARTS = frozenset({".git", ".github", ".claudron", "__pycache__"})

#: On every generated file. Its absence is what `validate` warns about, and what
#: tells a human the file is not theirs to edit.
HEADER = "<!-- generated by claudron index --navigation; do not hand-edit -->"

#: Where preserved entries go. Marked, so the next reader can see that this part
#: is NOT derived and why -- an unmarked preserved line would read as generated
#: and quietly become untrustworthy.
PRESERVED_HEADING = "## Not derived from the index"
PRESERVED_NOTE = (
    "These entries were in this file and are not in the index, but their target "
    "exists. They are kept verbatim rather than dropped -- see "
    "`claudron/navigation.py`. Remove the target or index it to resolve."
)

#: `- [Title](target)` -- the link is what an entry is KEYED on. The outage's
#: six conflicts were all resolved by keying on link target and taking the
#: union, so that is the key here too.
_ENTRY_RE = re.compile(
    r"^\s*[-*]\s*\[(?P<title>[^\]]*)\]\((?P<target>[^)]+)\)(?P<rest>.*)$")

#: The trailing `(status: …, owner: …, tags: …)` clause `_fmt_entry` renders.
#: Anchored to the END *and* to a known leading label, so a description that
#: itself ends in parentheses is never mistaken for metadata and truncated.
#:
#: `.*` RATHER THAN `[^()]*`, and this is load-bearing: a frontmatter VALUE may
#: itself contain parentheses. A real note in this estate carries
#: `status: draft — lens input for ari's 3-lens synthesis (NO PR yet)`, whose
#: rendered clause therefore nests. A class that cannot cross the inner `)`
#: fails to strip the tail, the whole clause is read back as part of the
#: description, and `_fmt_entry` then appends a FRESH clause -- so the line
#: grows by one copy on EVERY run, without bound. Measured before this fix: one
#: file rewritten on every pass, five copies and counting.
#:
#: BUILT FROM `_META_LABELS` rather than repeating it. A field added to the
#: renderer but missing from this pattern is not cosmetic drift -- it is that
#: same unbounded growth re-entering, because the clause stops being stripped.
_META_LABELS = ("status", "owner", "tags")
_META_OPEN_RE = re.compile(r"\((?:" + "|".join(_META_LABELS) + r"):")


@dataclass(frozen=True)
class DirectoryRender:
    """One directory's rendered file and everything it could not simply derive.

    A record rather than a widening tuple: three of the four slots are
    `list[str]` and positionally interchangeable, so a swap would typecheck
    silently — and adding `carried` already widened a 3-tuple to a 4-tuple and
    forced a mechanical edit at every call site, none of which used the new
    value. Deliberately NOT `NavigationResult`, which is the sweep-level
    aggregate keyed by relative path; a directory does not know its own key."""

    text: str
    preserved: list[str]
    dropped: list[str]
    carried: list[str]


@dataclass
class NavigationResult:
    """What was written, and everything it could not simply derive.

    #1742's rule applies to this door as much as to any read door: a caller
    must be able to say what it generated from, what it skipped, and what it
    could not resolve, without reading the source."""

    written: list[Path] = field(default_factory=list)
    unchanged: list[Path] = field(default_factory=list)
    preserved: dict[str, list[str]] = field(default_factory=dict)
    dropped: dict[str, list[str]] = field(default_factory=dict)
    carried: dict[str, list[str]] = field(default_factory=dict)
    skipped: dict[str, str] = field(default_factory=dict)
    entries_seen: int = 0
    directories_considered: int = 0

    @staticmethod
    def _n(d: dict[str, list]) -> int:
        return sum(len(v) for v in d.values())

    def bound_lines(self) -> list[str]:
        n_pres, n_drop, n_carr = (self._n(self.preserved), self._n(self.dropped),
                                  self._n(self.carried))
        lines = [
            f"GENERATED FROM: the index ({self.entries_seen} entry(ies)) — the "
            "notes' own frontmatter, plus only what the previous file held that "
            "the index could not supply (see NOT DERIVED)",
            f"DIRECTORIES   : {self.directories_considered} considered, "
            f"{len(self.written)} written, {len(self.unchanged)} already current",
        ]
        if self.skipped:
            lines.append(f"SKIPPED       : {len(self.skipped)} — "
                         + "; ".join(f"{k}: {v}" for k, v in
                                     sorted(self.skipped.items())[:3])
                         + (" …" if len(self.skipped) > 3 else ""))
        lines.append(
            f"NOT DERIVED   : {n_pres} entry(ies) PRESERVED (in the file, not in "
            f"the index, target exists) · {n_drop} DROPPED (target missing) · "
            f"{n_carr} DESCRIPTION(S) CARRIED (note has no `description:`)")
        # DERIVED, never a hand-synced guard: a guard listing two of the three
        # dicts prints the detail AND "nothing was unaccounted for" together --
        # a false all-clear beside its own refutation, in the one output whose
        # whole job is coverage honesty. It has already been widened once.
        detail = [f"  preserved in {p}: {', '.join(v)}"
                  for p, v in sorted(self.preserved.items())]
        detail += [f"  dropped from {p}: {', '.join(v)}"
                   for p, v in sorted(self.dropped.items())]
        detail += [f"  carried in {p}: {len(v)} description(s)"
                   for p, v in sorted(self.carried.items())]
        if n_carr:
            detail.append("                to stop carrying: add `description:` "
                          "to the note's frontmatter; the note always wins")
        lines += detail or ["                nothing in any file was unaccounted for"]
        return lines


def _target(e: dict) -> str:
    """The entry's link target, derived ONCE from the fact the index carries.

    `filename` is the stem, so `stem + ".md"` agrees with `path` only by
    convention -- and three hand-written copies of that convention is how the
    rendered link and the known-target set drift apart."""
    raw = e.get("path")
    return Path(raw).name if raw else f"{e.get('filename', '')}.md"


def _fmt_entry(e: dict, desc: str = "") -> str:
    """The fleet protocol's exact line (Claudlobby
    `library/protocols/shared-documentation.md`):

        - [Title](file.md) — description (status: X, owner: Y, tags: a, b)

    An empty field is OMITTED rather than rendered blank -- `(status: , owner: )`
    is noise a reader has to parse past, and the protocol's readers key on the
    labels rather than on position.

    `desc` arrives ALREADY RESOLVED. The frontmatter-wins-over-carried rule is
    `render_navigation`'s, stated once there; a second copy here would be dead
    (the caller never passes both) and a reader could not tell which was live."""
    title = e.get("title") or e.get("filename") or "untitled"
    line = f"- [{title}]({_target(e)})"
    if desc:
        line += f" — {desc}"
    bits = []
    for label in _META_LABELS:
        val = e.get(label)
        if not val:
            continue
        bits.append(f"{label}: " +
                    (", ".join(val) if isinstance(val, list) else str(val)))
    if bits:
        line += " (" + ", ".join(bits) + ")"
    return line


def _entries_by_directory(index: dict, vault_root: Path) -> dict[Path, list[dict]]:
    """Every index entry, grouped by the resolved directory its note sits in.

    ONE pass over the entries for the whole sweep. Grouping per directory
    instead meant rescanning all of them and re-`resolve()`ing every parent once
    per directory: on this estate's vault (830 entries, 42 directories) that is
    ~35k iterations and ~70k `resolve()` calls, against ~830 here. It matters
    because this door is meant to run on every capture."""
    groups: dict[Path, list[dict]] = {}
    # `resolve()` is ~95x the cost of `.parent` and is invariant across every
    # note in a directory, so it is memoized: 42 calls for this estate's vault
    # rather than 830.
    resolved: dict[Path, Path | None] = {}
    for e in index.get("entries", []):
        raw = e.get("path")
        if not raw:
            continue
        parent = (vault_root / raw).parent
        if parent not in resolved:
            try:
                resolved[parent] = parent.resolve()
            except (OSError, ValueError):
                resolved[parent] = None
        target = resolved[parent]
        if target is None:
            continue
        groups.setdefault(target, []).append(e)
    # Deterministic: newest first, then title -- ordering churn is itself a
    # diff nobody wants to read.
    for entries in groups.values():
        entries.sort(key=lambda e: (str(e.get("updated", "")), str(e.get("title", ""))),
                     reverse=True)
    return groups


def _entries_for(index: dict, vault_root: Path, directory: Path,
                 groups: dict[Path, list[dict]] | None = None) -> list[dict]:
    """Index entries whose note sits DIRECTLY inside `directory`."""
    if groups is None:
        groups = _entries_by_directory(index, vault_root)
    try:
        return groups.get(directory.resolve(), [])
    except (OSError, ValueError):
        return []


def classify_existing(existing_text: str, directory: Path,
                      known_targets: set[str]) -> tuple[list[str], list[str]]:
    """Split the file's current entries into (preserve, drop).

    The ruling, and the whole reason this function is separate and tested: an
    entry the index does not know about is NEVER silently discarded. Whether it
    survives turns on one observable fact -- does its target exist on disk --
    because that is what decides whether there is anything left to navigate to.
    """
    preserve: list[str] = []
    drop: list[str] = []
    for raw in existing_text.splitlines():
        m = _ENTRY_RE.match(raw)
        if not m:
            continue
        target = m.group("target").strip()
        if target in known_targets:
            continue                      # derived afresh; nothing to preserve
        if (directory / target).exists():
            preserve.append(raw.rstrip())
        else:
            drop.append(f"[{m.group('title')}]({target})")
    return preserve, drop


def _strip_meta_tail(rest: str) -> str:
    """`rest` minus the trailing `(status: …, owner: …, tags: …)` clause.

    THE LAST label-opening wins, not the first, and not a plain regex. Two real
    shapes defeat the obvious patterns, in opposite directions:

    * a metadata VALUE may contain parentheses (`status: draft — lens input …
      (NO PR yet)`), so a `[^()]*` class cannot reach the closing paren, fails
      to strip, and the clause is read back as the description -- which is the
      unbounded-growth defect, since a fresh clause is then appended every run;
    * a DESCRIPTION may contain a `(status: …)`-shaped substring, and a greedy
      `.*` anchored to the first opening swallows everything from there to the
      end of the line -- silently truncating the prose.

    Taking the LAST opening handles both, and matches the one thing the
    renderer guarantees: the metadata clause is always last on the line."""
    last = None
    for m in _META_OPEN_RE.finditer(rest):
        last = m
    if last is None or not rest[last.start():].rstrip().endswith(")"):
        return rest.strip()
    return rest[:last.start()].strip()


def existing_descriptions(existing_text: str) -> dict[str, str]:
    """`{target: description}` for every entry in the file that carries one.

    THE SECOND HALF OF THE RULING, and it was found by running the door against
    a real vault rather than a fixture. The entry-level rule protects an entry
    the index does not know about; it does NOT protect the DESCRIPTION of an
    entry the index *does* know about, and the index only has one when the note
    carries `description:` in its frontmatter. Measured on this estate's vault:
    of 476 entries across 22 hand-maintained `INDEX.md` files, 457 carried a
    hand-written description and **235 of them would have been deleted** -- 20
    of the 22 files -- while the run reported `nothing in any file was
    unaccounted for`. That is the module's own definition of a silent deletion,
    one level down, so the same answer applies: the note's frontmatter wins when
    it has one, and the file's text is kept when it does not.

    Idempotent by construction: a carried description is rendered back into the
    file, so the next run reads it here again and carries it again."""
    out: dict[str, str] = {}
    for raw in existing_text.splitlines():
        m = _ENTRY_RE.match(raw)
        if not m:
            continue
        rest = (m.group("rest") or "").strip()
        if not rest.startswith("—"):
            continue
        desc = _strip_meta_tail(rest[1:])
        if desc:
            out[m.group("target").strip()] = desc
    return out


def render_navigation(vault: "Vault", directory: Path, index: dict,
                      *, existing_text: str = "",
                      groups: dict[Path, list[dict]] | None = None) -> DirectoryRender:
    """One directory's `DirectoryRender` — a PURE function of the index plus
    whatever the existing file holds that the index does not."""
    entries = _entries_for(index, Path(vault.root), directory, groups)
    known = {_target(e) for e in entries}
    preserved, dropped = classify_existing(existing_text, directory, known)
    have = existing_descriptions(existing_text)

    carried: list[str] = []
    rendered: list[str] = []
    for e in entries:
        # THE PRECEDENCE, STATED ONCE. The note's frontmatter wins wherever it
        # has one -- that disagreement is the conflict class this door removes.
        # Only where it is silent does the file's own text survive.
        tgt = _target(e)
        desc = (e.get("description") or "").strip()
        if not desc:
            desc = have.get(tgt, "")
            if desc:
                carried.append(tgt)
        rendered.append(_fmt_entry(e, desc))

    lines = [HEADER, "", f"# Index: {directory.name}", ""]
    lines.extend(rendered)
    if not entries:
        lines.append("_No indexed notes in this directory._")
    if preserved:
        lines.extend(["", PRESERVED_HEADING, "", PRESERVED_NOTE, ""])
        lines.extend(preserved)
    return DirectoryRender("\n".join(lines).rstrip() + "\n",
                           preserved, dropped, carried)


def _candidate_directories(vault: "Vault", index: dict) -> list[Path]:
    """Every directory the index actually has a note in, plus any that already
    carries an `INDEX.md`.

    The second half matters and is not redundant: a directory whose notes have
    all been deleted still has a stale `INDEX.md` full of dangling entries, and
    a walk driven by the index alone would never visit it -- leaving the worst
    files untouched precisely because they are the emptiest.

    BOTH HALVES ARE SCOPED TO `note_tiers()`, and the second one has to be said
    out loud because a bare `root.rglob` is the obvious way to write it and is
    wrong. `vault.note_tiers` is the shared scope `build_index` walks, and its
    own docstring names this exact construct as the bug it exists to prevent: it
    never descends a fleet's `library/`/`voices/`/`runtime/`, which are
    Claudlobby overlay content rather than notes. This door is a WRITER with no
    business reaching further than the indexer that feeds it -- measured on a
    probe vault, the unscoped sweep wrote a generated, header-stamped `INDEX.md`
    into `<fleet>/library/`, `<fleet>/voices/`, `<fleet>/runtime/` AND a bot's
    `runtime/bots/<b>/projects/<repo>/` git checkout, replacing a hand-written
    entry with `_No indexed notes in this directory._` because no index entry
    can ever live there. The first half needs no such guard: every indexed note
    is inside a tier by construction."""
    from .vault import note_tiers

    root = Path(vault.root)
    dirs: set[Path] = set()
    for e in index.get("entries", []):
        raw = e.get("path")
        if raw:
            dirs.add((root / raw).parent)
    for base, _tier in note_tiers(vault):
        if not base.is_dir():
            continue
        for existing in base.rglob("INDEX.md"):
            if _SKIP_PARTS.isdisjoint(existing.parts):
                dirs.add(existing.parent)
    return sorted(dirs)


def write_navigation(vault: "Vault", *, directories=None,
                     index: dict | None = None) -> NavigationResult:
    """Regenerate `INDEX.md` for each directory. Idempotent: unchanged content
    is not rewritten, so running twice changes nothing and a no-op costs no
    commit.

    Takes `vault_write_lock` ONCE around the whole sweep rather than per file:
    the caller's mental model is "the navigation is now correct", and a sweep
    that another writer can interleave with delivers half of that.
    """
    from .knowledge import ensure_index
    from .locking import atomic_write_text, vault_write_lock
    from .vault import is_within_root

    if index is None:
        # `ensure_index` is the one home of the freshness policy (lookup and the
        # write engine both go through it); `load_index() or build_index()` here
        # would be a second copy of it.
        index = ensure_index(vault)
    result = NavigationResult(entries_seen=len(index.get("entries", [])))

    groups = _entries_by_directory(index, Path(vault.root))

    with vault_write_lock(vault):
        targets = ([Path(d) for d in directories]
                   if directories is not None else _candidate_directories(vault, index))
        result.directories_considered = len(targets)
        for directory in targets:
            rel = _rel(vault, directory)
            if not directory.is_dir():
                result.skipped[rel] = "not a directory"
                continue
            # The shared containment primitive every other write path uses
            # (engine, promote, validate --fix). It matters here because
            # `directories=` is caller-supplied: without it this is the one
            # writer in the package that would write through a symlinked tier.
            if not is_within_root(directory, Path(vault.root)):
                result.skipped[rel] = "outside the vault root (or reached via a symlink)"
                continue
            path = directory / "INDEX.md"
            try:
                existing = path.read_text() if path.exists() else ""
            except OSError as exc:
                # UNREADABLE IS NOT EMPTY: treating it as empty would discard
                # every hand-written entry in it, which is the exact harm the
                # preserve ruling exists to prevent.
                result.skipped[rel] = f"existing INDEX.md unreadable ({exc.__class__.__name__})"
                continue
            r = render_navigation(vault, directory, index,
                                  existing_text=existing, groups=groups)
            if r.preserved:
                result.preserved[rel] = r.preserved
            if r.dropped:
                result.dropped[rel] = r.dropped
            if r.carried:
                result.carried[rel] = r.carried
            text = r.text
            if existing == text:
                result.unchanged.append(path)
                continue
            try:
                atomic_write_text(path, text)
            except OSError as exc:
                result.skipped[rel] = f"write failed ({exc.__class__.__name__})"
                continue
            result.written.append(path)
    return result


def _rel(vault: "Vault", directory: Path) -> str:
    try:
        return str(directory.relative_to(Path(vault.root)))
    except ValueError:
        return str(directory)
